import * as fs from 'fs';
import * as path from 'path';

function c(id: string, title: string, cat: string, ind: string, diff: string, prompt: string, ctx: string, facts: string[], hints: string[], calcs: string[], crit: string[]) {
  return { id, title, category: cat, industry: ind, difficulty: diff, prompt, context: ctx, keyFacts: facts, frameworkHints: hints, expectedCalculations: calcs, successCriteria: crit };
}

const moreCases: any[] = [
  // NEW BUSINESS / INNOVATION (18 more to reach 20+)
  c('nb-07','Autonomous Vehicle Mobility Service','New Business / Innovation','Automotive / Mobility','Expert',
    'An automaker ($80B revenue) wants to launch an autonomous ride-hailing service in 5 cities. Investment: $5B. Expected to break even in 7 years.',
    'Current: traditional auto manufacturer. AV technology: Level 4 pilot in 2 cities. Target: 1,000 vehicles in 5 cities. Competitor: Waymo (operational), Cruise (paused).',
    ['Revenue: $80B (traditional auto)','AV investment: $5B','Target cities: 5','Vehicles: 1,000 (Level 4)','Break-even: 7 years','Competitor: Waymo (1,000+ vehicles, 3 cities)','Technology: Level 4 pilot in 2 cities','Ride-hailing market: $200B by 2030','Current utilization: 18 hours/day (need 20)','Revenue per vehicle: $100K/year (need $200K)','Regulatory: 15 states permit AV operation','Safety: 1 incident per 1M miles (human: 1 per 100K)'],
    ['City selection and market sizing','AV fleet deployment strategy (1,000 vehicles)','Technology and safety validation timeline','Regulatory and permitting strategy','Pricing and unit economics model'],
    ['Fleet deployment: 1,000 vehicles across 5 cities','Revenue per vehicle: $200K/year = $200M total','Unit economics: positive contribution margin by Year 3','Safety record: achieve 10x better than human drivers','Break-even timeline: 7 years'],
    ['AV mobility service launch strategy','City prioritization and market sizing','Technology and safety roadmap','Financial model with 7-year break-even plan','Regulatory and partnership strategy']),
  c('nb-08','Space-Based Earth Observation Startup','New Business / Innovation','Space / Technology','Expert',
    'A satellite startup ($0 revenue, $500M raised) wants to build a constellation of 100 small satellites for real-time Earth observation. Target market: agriculture, defense, climate.',
    'Pre-revenue, $500M raised. Constellation cost: $2B. 100 small satellites, 1m resolution. Target customers: governments (40%), agriculture (30%), commercial (30%).',
    ['Revenue: $0 (pre-revenue)','Funding raised: $500M','Constellation cost: $2B (100 satellites)','Satellite cost: $15M each','Launch cost: $5M each (SpaceX rideshare)','Resolution: 1m (competitor: 30cm)','Time to first satellite: 18 months','Full constellation: 36 months','Target market: agriculture 30%, defense 40%, commercial 30%','Competitor: Planet (200 satellites), Maxar, BlackSky','TAM: $15B by 2030','Current team: 200 (need 500)'],
    ['Constellation design (orbits, coverage, revisit rate)','Satellite manufacturing and launch strategy','Data platform and analytics services','Customer acquisition: government, agriculture, commercial','Funding strategy for remaining $1.5B'],
    ['First satellite launch: 18 months','Full constellation: 36 months','Revenue target: $100M by Year 5','Customer contracts: 50 by launch','Capital efficiency: $20M per satellite (benchmark)'],
    ['Space-based Earth observation business strategy','Satellite constellation and launch plan','Data platform and analytics offering','Customer and market strategy','Financial model and funding plan']),
  c('nb-09','Vertical Farming Network Expansion','New Business / Innovation','Agriculture / Food Tech','Hard',
    'A vertical farming startup ($50M revenue) wants to expand from 2 to 20 facilities nationally. Current: profitable in leafy greens, wants to add herbs and berries.',
    '2 facilities, $50M revenue, 15% EBITDA margin. Leafy greens only. Expansion: $500M capital for 18 new facilities. Competitor: AeroFarms (bankrupt), Plenty (struggling).',
    ['Revenue: $50M (2 facilities)','EBITDA margin: 15% ($7.5M)','Product: leafy greens only','Expansion: 18 new facilities (20 total)','Capital required: $500M','Revenue per facility: $25M','Competitor: AeroFarms (bankrupt), Plenty (struggling)','Cost per pound: $2 (benchmark outdoor: $1)','Energy cost: 30% of operating cost','Water usage: 95% less than outdoor farming','Retail customers: 50 grocery chains','Market: indoor farming $5B by 2028'],
    ['Facility site selection (energy cost, proximity to market)','Crop expansion: herbs, berries, microgreens','Technology improvements: LED efficiency, automation','Customer expansion: new retail and food service','Capital raise: $500M equity and debt'],
    ['Facility expansion: 2 to 20 in 3 years','Revenue: $50M to $500M','EBITDA margin: 15% to 25% at scale','Product mix: leafy greens 50%, herbs 30%, berries 20%','Unit economics: positive contribution margin by facility #5'],
    ['Vertical farming network expansion strategy','Technology and crop diversification plan','Customer and market development','Capital and funding strategy','Financial model with 20-facility network economics']),
  c('nb-10','Plant-Based Meat 2.0 Product Launch','New Business / Innovation','Food Tech / CPG','Medium',
    'A food tech startup ($30M revenue) has developed a new plant-based meat using precision fermentation. They need to launch nationally and scale to $500M revenue.',
    'Current: $30M revenue, specialty retail only. New product: indistinguishable from real meat (blind taste test 85% preference). Retail price: $8/lb (real meat: $6/lb).',
    ['Revenue: $30M (specialty retail only)','New product: precision fermentation plant-based meat','Taste test: 85% preference over competitor','Price: $8/lb (real meat $6/lb, competitor $10/lb)','Distribution: specialty retail only (need national)','Manufacturing: 1 facility (need 3)','Customers: 5,000 retail doors (need 50,000)','Marketing budget: $50M','Competitor: Impossible, Beyond Meat (struggling)','Market: plant-based meat $15B by 2030','Shelf life: 21 days (need 45 days)'],
    ['National retail launch strategy (50K doors in 12 months)','Manufacturing scale-up: 3 facilities','Food service channel entry (restaurants, universities)','Marketing and brand building campaign','Supply chain for precision fermentation ingredients'],
    ['Revenue: $30M to $500M in 3 years','Distribution: 5K to 50K retail doors','Price parity with real meat: $8 to $6/lb','Manufacturing: 3 facilities at full capacity','Brand awareness: 0% to 40% in target demographic'],
    ['Plant-based meat 2.0 national launch strategy','Manufacturing and supply chain scale-up','Retail and food service channel strategy','Marketing and brand building plan','Financial model with $500M revenue target']),
  c('nb-11','Cybersecurity Managed Service for SMBs','New Business / Innovation','Cybersecurity / Technology','Medium',
    'A cybersecurity company ($200M revenue) wants to launch a managed security service for SMBs (100-1,000 employees). Market is underserved: 60% of SMBs have no security.',
    'Current: enterprise cybersecurity ($200M revenue). SMB market: 30M companies, 60% unprotected. Competitor: mostly enterprise-focused. Price point: $500/month per company.',
    ['Revenue: $200M (enterprise only)','SMB target market: 30M companies (100-1,000 employees)','SMB security gap: 60% have no protection','Price point: $500/month per company','TAM: $180B (30M x $500 x 12)','Competitor: enterprise-focused (CrowdStrike, Palo Alto)','Technology: existing platform needs SMB adaptation','Sales model: PLG + inside sales (not field sales)','Customer acquisition cost: $2,000 (target LTV: $18,000)','Churn: target 5% monthly (benchmark 3%)','Revenue model: subscription + incident response fees'],
    ['SMB-specific product bundle (endpoint, email, network, compliance)','PLG (product-led growth) acquisition funnel','Inside sales team and customer success','Partner channel: MSPs, VARs, accountants','Compliance add-on (SOC 2, HIPAA, PCI for SMBs)'],
    ['SMB customers: 0 to 10,000 in 3 years','Revenue: $0 to $60M from SMB segment','CAC: $2,000 (LTV/CAC: 9x)','Churn: 5% to 3% monthly','Gross margin: 70%+ on managed services'],
    ['SMB cybersecurity managed service strategy','Product and pricing design','PLG and inside sales go-to-market','Partner channel strategy','Financial model with $60M revenue target']),
  c('nb-12','Digital Health Wearable Platform','New Business / Innovation','Healthcare / Wearables','Hard',
    'A health tech company ($100M revenue) wants to launch a medical-grade wearable that monitors 10 health metrics. Target: 1M devices sold in Year 1.',
    'Current: health data analytics ($100M revenue). New: FDA-cleared wearable. Metrics: heart rate, SpO2, ECG, blood pressure, glucose (non-invasive), temperature, sleep, stress, activity, respiratory rate.',
    ['Revenue: $100M (analytics only)','New product: medical-grade wearable','Price: $299 (consumer: $199, medical: $399)','FDA clearance: Class II (6-month timeline)','Battery life: 7 days (competitor: 2 days)','Accuracy: 95% (medical-grade threshold)','Target: 1M devices Year 1, 5M Year 3','Recurring revenue: $10/month subscription','Competitor: Apple Watch (consumer), Dexcom (glucose)','Non-invasive glucose: breakthrough technology (if achieved)','Manufacturing: contract manufacturer, $200M upfront','Marketing budget: $100M Year 1'],
    ['FDA clearance strategy and clinical trials','Device manufacturing and supply chain','Software platform and health analytics','Consumer and medical channel distribution','Subscription and recurring revenue model'],
    ['Device sales: 1M Year 1, 5M Year 3','Revenue: $100M devices + $120M subscription Year 1','FDA clearance: achieve Class II approval','Accuracy: 95% across all 10 metrics','Gross margin: 50% devices, 80% subscription'],
    ['Medical wearable launch strategy','FDA and clinical trial roadmap','Manufacturing and distribution plan','Software platform and analytics','Financial model with device + subscription revenue']),
  c('nb-13','Electric Aircraft Regional Routes','New Business / Innovation','Aviation / Clean Tech','Expert',
    'An aviation startup ($0 revenue, $1B raised) wants to launch electric short-haul flights (500-mile routes). Fleet: 50 electric aircraft. Target: 20 routes by Year 3.',
    'Pre-revenue, $1B raised. Electric aircraft: 19-seater, 500-mile range. Aircraft cost: $10M each. Operating cost: 70% less than jet fuel. Competitor: Heart Aerospace, Eviation.',
    ['Revenue: $0 (pre-revenue)','Funding: $1B raised (need $2B total)','Aircraft: 19-seater electric','Range: 500 miles','Aircraft cost: $10M each (50 = $500M)','Operating cost: 70% less than jet fuel','Competitor: Heart Aerospace (ES-30), Eviation (Alice)','FAA certification: 3-year timeline','First delivery: Year 2','Full fleet: Year 5','Routes: 20 regional routes by Year 3','Ticket price: 30% below comparable','Passengers per flight: 14 average (74% load factor)'],
    ['FAA certification and type certificate strategy','Aircraft procurement and fleet management','Route selection and airport partnerships','Charging infrastructure at airports','Revenue management and pricing strategy'],
    ['FAA certification: achieve by Year 2','Fleet deployment: 50 aircraft over 5 years','Routes: 20 profitable regional routes','Operating cost: 70% reduction vs jet fuel','Break-even: Year 4 on route level'],
    ['Electric aviation business strategy','FAA certification and regulatory roadmap','Fleet and route planning','Infrastructure and partnerships','Financial model with 5-year fleet deployment']),
  c('nb-14','AI-Powered Legal Services Platform','New Business / Innovation','Legal / Technology','Medium',
    'A legal tech startup ($20M revenue) wants to build an AI platform that handles routine legal work (contracts, compliance, IP filings). Target: 10K law firms.',
    'Current: $20M revenue from contract review tool. New: full legal services platform. AI handles 80% of routine legal work. Price: $500/month per firm.',
    ['Revenue: $20M (contract review tool only)','New platform: AI-powered legal services','Target: 10K law firms','Price: $500/month per firm','TAM: $60B (routine legal work)','AI capability: handles 80% of routine work','Competitor: Harvey AI, Casetext (acquired by Thomson Reuters)','Accuracy: 95% (human lawyer: 99%)','Time savings: 70% reduction in document drafting','Ethical considerations: unauthorized practice of law','Regulatory: varies by jurisdiction','Sales cycle: 3-6 months for law firms'],
    ['AI model training on legal datasets (contracts, compliance, IP)','Law firm acquisition strategy (PLG + partnerships)','Ethical AI framework and liability management','Regulatory compliance by jurisdiction','Integration with existing legal practice management'],
    ['Law firm customers: 0 to 10,000 in 3 years','Revenue: $20M to $200M','AI accuracy: 95% to 99%','Time savings: 70% to 85%','Product liability: zero malpractice claims'],
    ['AI legal services platform strategy','AI model and accuracy improvement plan','Law firm go-to-market strategy','Ethical and regulatory framework','Financial model with $200M revenue target']),
  c('nb-15','Subscription Car Service (No Ownership)','New Business / Innovation','Automotive / Mobility','Hard',
    'An automotive company ($60B revenue) wants to launch a subscription car service where customers never own a car. Monthly fee includes insurance, maintenance, and unlimited swaps.',
    'Subscription: $500/month (compact), $800/month (sedan), $1,200/month (SUV). Includes insurance, maintenance, roadside, 1 swap/month. Fleet: 50,000 vehicles.',
    ['Revenue: $60B (traditional sales)','New service: subscription car model','Price: $500-$1,200/month','Includes: insurance, maintenance, swaps','Fleet: 50,000 vehicles (Year 1, need 200K)','Customer acquisition cost: $2,000','Target customer: urban professionals 25-40','Churn: 5% monthly (benchmark 3%)','Vehicle utilization: 85% (need 90%)','Competitor: Care by Volvo, Porsche Drive','Market: subscription economy growing 20% annually','Unit economics: positive at 18 months per vehicle'],
    ['Subscription tier design and pricing','Fleet management and vehicle lifecycle','Customer acquisition and retention','Insurance and maintenance cost optimization','Technology platform (app, vehicle access, swaps)'],
    ['Fleet size: 50K to 200K in 3 years','Revenue: $0 to $1B from subscriptions','Customer churn: 5% to 3% monthly','Vehicle utilization: 85% to 90%','Unit economics: positive contribution by Month 18'],
    ['Subscription car service business model','Fleet and operations strategy','Customer acquisition and pricing','Technology platform design','Financial model with unit economics per vehicle']),
  c('nb-16','Carbon Capture and Trading Platform','New Business / Innovation','Climate Tech / Energy','Expert',
    'A climate tech startup ($10M revenue) wants to build a carbon capture technology and digital trading platform. Target: capture 1M tonnes/year and trade carbon credits.',
    'Current: pilot carbon capture facility (10K tonnes/year). New: scale to 1M tonnes and build trading platform. Cost: $100/tonne (need $50). Market price: $30-80/tonne.',
    ['Revenue: $10M (carbon credits, pilot)','Pilot capacity: 10K tonnes/year','Target: 1M tonnes/year','Capture cost: $100/tonne (need $50)','Market price: $30-80/tonne (volatile)','Technology: direct air capture (DAC)','Facility cost: $500M for 1M tonnes','Trading platform: digital marketplace','Competitor: Climeworks, Carbon Engineering, 1PointFive','Policy: IRA 45Q tax credit ($180/tonne US)','Demand: voluntary + compliance markets growing 30% annually','Team: 100 (need 500)'],
    ['Technology scale-up from 10K to 1M tonnes','Carbon credit trading platform development','Policy and regulatory strategy (45Q, EU ETS)','Customer contracts (voluntary + compliance markets)','Facility financing and construction'],
    ['Capture capacity: 10K to 1M tonnes/year','Cost per tonne: $100 to $50','Revenue: $10M to $200M (trading platform + credits)','Tax credit optimization: $180/tonne 45Q','Platform: 100+ corporate buyers on trading platform'],
    ['Carbon capture and trading business strategy','Technology and facility scale-up plan','Trading platform development','Policy and regulatory strategy','Financial model with 5-year scaling roadmap']),
  c('nb-17','Robotic Restaurant Kitchen','New Business / Innovation','Food Tech / Robotics','Hard',
    'A robotics startup ($5M revenue) has developed a robotic kitchen that can cook 100 menu items. They want to launch 50 ghost kitchens in major cities.',
    'Current: 2 pilot locations, $5M revenue. Robot cost: $250K each. Menu: 100 items. Cooking time: 3 minutes. Accuracy: 99%. Competitor: Miso Robotics (Flippy).',
    ['Revenue: $5M (2 pilot locations)','Robot cost: $250K each','Menu: 100 items','Cooking time: 3 minutes (human: 12 minutes)','Accuracy: 99%','Ghost kitchen model: 50 locations','Revenue per location: $1.5M/year','Target: 50 ghost kitchens in 3 years','Competitor: Miso Robotics (Flippy), Nuro','Labor: 1 person per kitchen (vs 5 human)','Food cost: 28% (human kitchen: 35%)','Delivery platforms: 30% commission'],
    ['Robot manufacturing scale-up (50 units)','Ghost kitchen site selection and launch','Menu optimization for robotic cooking','Delivery platform partnerships and direct ordering','Franchise or company-owned model decision'],
    ['Ghost kitchens: 2 to 50 in 3 years','Revenue: $5M to $75M','Labor cost: 70% reduction vs human kitchen','Food cost: 28% (7% improvement)','Payback period: 12 months per kitchen'],
    ['Robotic kitchen ghost network strategy','Robot manufacturing and deployment','Kitchen operations and menu design','Customer acquisition and ordering platforms','Financial model with 50-kitchen network economics']),
  c('nb-18','Drone Delivery Network (Last-Mile)','New Business / Innovation','Logistics / Drone Tech','Expert',
    'A drone delivery startup ($10M revenue) has FAA Part 135 certification. They want to build a drone delivery network covering 10M households in 10 metropolitan areas.',
    'FAA Part 135 certified. Current: 50 drones, 2 cities. Drone cost: $20K each. Delivery range: 10 miles. Payload: 5 lbs. Time: 15 minutes (vs 2 hours by car).',
    ['Revenue: $10M (2 cities)','FAA Part 135 certification: obtained','Drones: 50 (need 500)','Drone cost: $20K each (500 = $10M)','Delivery range: 10 miles','Payload: 5 lbs','Delivery time: 15 minutes','Coverage target: 10M households in 10 metro areas','Competitor: Wing (Alphabet), Zipline (healthcare)','Delivery price: $5 (competitor: $10+)','Orders per drone per day: 20 (need 30)','Unit economics: positive at 15+ orders/day'],
    ['Drone fleet expansion: 50 to 500','Metropolitan area expansion (10 cities)','Customer partnerships (retail, pharmacy, food)','Airspace management and BVLOS operations','Maintenance and operations infrastructure'],
    ['Fleet: 50 to 500 drones','Coverage: 2 to 10 metropolitan areas','Orders per drone: 20 to 30 per day','Revenue: $10M to $100M','Unit economics: positive by Year 2'],
    ['Drone delivery network expansion strategy','Fleet and airspace operations','Customer and partnership strategy','Regulatory and safety framework','Financial model with 10-city network plan']),
  c('nb-19','Personalized Nutrition AI Platform','New Business / Innovation','Health Tech / Food Tech','Medium',
    'A health tech startup ($15M revenue) wants to launch an AI-powered personalized nutrition platform using gut microbiome testing. Target: 2M subscribers.',
    'Current: $15M revenue from wellness app. New: gut microbiome test + AI meal plans. Price: $200 test + $30/month subscription. Competitor: ZOE, Viome.',
    ['Revenue: $15M (wellness app)','New product: microbiome-based nutrition AI','Test cost: $200','Subscription: $30/month','Target: 2M subscribers in 3 years','Competitor: ZOE ($100 test + $30/month), Viome','Science: gut microbiome links to 20+ health conditions','Accuracy: personalized recommendations improve outcomes 40%','Lab partner: 2 CLIA-certified labs','Time to result: 2 weeks (need 5 days)','Retention: 60% at 12 months (benchmark 70%)'],
    ['Microbiome testing and lab partnership','AI nutrition recommendation engine','Content and meal planning platform','Customer acquisition (DTC + healthcare partnerships)','Clinical validation and published research'],
    ['Subscribers: 0 to 2M in 3 years','Revenue: $15M to $250M','Test turnaround: 2 weeks to 5 days','Retention: 60% to 70% at 12 months','Clinical outcomes: 40% improvement in health markers'],
    ['Personalized nutrition platform strategy','AI and microbiome science capabilities','Customer acquisition and retention','Clinical validation and partnerships','Financial model with 2M subscriber target']),
  c('nb-20','Electric Boat Rental Network','New Business / Innovation','Clean Tech / Maritime / Tourism','Medium',
    'A clean tech startup ($5M revenue) wants to build an electric boat rental network in 20 coastal/tourist cities. 1,000 boats, 500 charging stations.',
    'Current: 2 cities, 50 boats, $5M revenue. Electric boats: 20ft, 4-hour range. Price: $100/hour. Competitor: few electric options. Tourism market: $1T globally.',
    ['Revenue: $5M (2 cities, 50 boats)','Boat: 20ft electric, 4-hour range','Price: $100/hour','Boat cost: $50K each (1,000 = $50M)','Charging stations: 500 ($5K each = $2.5M)','Expansion: 20 cities in 3 years','Revenue per boat: $100K/year (need $150K)','Utilization: 40% (need 60%)','Competitor: few electric boat options','Market: boat rental $15B globally','Tourism recovery: 120% of pre-COVID in target cities','Regulatory: marina permits, safety certifications'],
    ['Fleet manufacturing and procurement (1,000 boats)','Charging infrastructure deployment (500 stations)','City expansion: 20 coastal/tourist cities','Customer acquisition: tourism platforms, direct','Operations and maintenance at scale'],
    ['Fleet: 50 to 1,000 boats','Cities: 2 to 20','Revenue: $5M to $150M','Utilization: 40% to 60%','Charging stations: 500 across 20 cities'],
    ['Electric boat rental network expansion strategy','Fleet and infrastructure deployment plan','City selection and market entry','Customer acquisition and partnerships','Financial model with 20-city network']),
  c('nb-21','AI Tutoring Platform (K-12 Education)','New Business / Innovation','Education / EdTech','Medium',
    'An edtech startup ($25M revenue) wants to launch an AI tutoring platform that adapts to each student. Target: 10M students in 3 years.',
    'Current: $25M from online courses. New: AI tutor that adapts in real-time. Price: $20/student/month. Competitor: Khanmigo, Duolingo Max.',
    ['Revenue: $25M (online courses)','New product: adaptive AI tutor','Price: $20/student/month','Target: 10M students in 3 years','Market: K-12 tutoring $100B globally','Competitor: Khanmigo, Duolingo MasterClass','AI capability: real-time adaptation, 50 subjects','Learning improvement: 2x faster than traditional','Teacher dashboard: progress and intervention alerts','Accessibility: 20 languages','School vs parent purchasing: 60% school, 40% parent'],
    ['AI tutor model training and subject expansion','School district sales and partnerships','Parent direct-to-consumer marketing','Teacher and administrator dashboard','Multi-language and accessibility features'],
    ['Students: 0 to 10M in 3 years','Revenue: $25M to $500M','Learning outcomes: 2x improvement','School partnerships: 1,000 districts','Subject coverage: 50 subjects in 20 languages'],
    ['AI tutoring platform strategy','AI model and content development','School district and parent go-to-market','Learning outcomes measurement and validation','Financial model with 10M student target']),
  c('nb-22','Smart Home Energy Management System','New Business / Innovation','Clean Tech / Smart Home','Easy',
    'A clean tech startup ($15M revenue) wants to launch a smart home energy system that reduces electricity bills by 40%. Target: 2M homes in 3 years.',
    'Current: smart thermostat ($15M revenue). New: complete home energy system (solar, battery, EV charger, smart panels). Price: $15,000 installed (before tax credits).',
    ['Revenue: $15M (smart thermostat only)','New product: complete home energy system','Components: solar panels, battery, EV charger, smart panel','Price: $15,000 installed (before 30% tax credit = $10,500)','Savings: $2,400/year (40% reduction)','Payback: 4.4 years','Target: 2M homes in 3 years','Competitor: Tesla Powerwall, Enphase, Sunrun','Installation: certified installer network (500 partners)','Financing: $0 down, 10-year loan ($100/month)','Net savings: $100/month ($200 savings - $100 loan)'],
    ['Home energy system product bundle','Installer network expansion (500 partners)','Financing and subscription options','Utility partnership and grid services','Smart home app and energy optimization AI'],
    ['Homes: 0 to 2M in 3 years','Revenue: $15M to $3B','Installer network: 500 to 2,000 partners','Customer savings: $2,400/year average','Payback period: <5 years for customer'],
    ['Smart home energy system launch strategy','Product and installation network plan','Financing and customer acquisition','Utility partnerships and grid services','Financial model with 2M home deployment']),
  c('nb-23','Virtual Reality Training Platform (Enterprise)','New Business / Innovation','VR / Enterprise Training','Medium',
    'A VR startup ($10M revenue) wants to launch an enterprise training platform for high-risk industries (oil & gas, healthcare, construction). Target: 5,000 enterprise clients.',
    'Current: $10M from VR gaming. New: enterprise training. VR training reduces incidents 40%, speeds learning 60%. Price: $500/employee/year. Competitor: Strivr, Mursion.',
    ['Revenue: $10M (VR gaming)','New product: enterprise VR training platform','Price: $500/employee/year','Target: 5,000 enterprise clients in 3 years','Industries: oil & gas, healthcare, construction, aviation','Training improvement: 60% faster learning, 40% fewer incidents','Competitor: Strivr, Mursion, Talespin','Market: enterprise VR training $12B by 2028','Hardware: Meta Quest 3, Apple Vision Pro','Content library: 100 pre-built training modules','Custom content development: $50K per module'],
    ['Enterprise VR training content library (100 modules)','Industry-specific solutions (oil & gas, healthcare, construction)','Enterprise sales team and channel partnerships','VR hardware partnerships and procurement','ROI measurement and analytics platform'],
    ['Enterprise clients: 0 to 5,000 in 3 years','Revenue: $10M to $250M','Content library: 100 to 500 modules','Employee reach: 0 to 5M trained','ROI proof: 40% incident reduction documented'],
    ['Enterprise VR training platform strategy','Content library and industry solution development','Enterprise sales and channel strategy','Hardware partnerships and deployment','Financial model with $250M revenue target']),
];

const jsonPath = path.join(__dirname, '../../data/generated-cases.json');
let existing: any[] = [];
try {
  existing = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
} catch(e) {}

const seen = new Set(existing.map(c => c.id));
const newCases = moreCases.filter(c => !seen.has(c.id));
const merged = [...existing, ...newCases];
fs.writeFileSync(jsonPath, JSON.stringify(merged, null, 0), 'utf-8');
console.log(`Added ${newCases.length} new cases. Total: ${merged.length}`);
const counts: Record<string, number> = {};
merged.forEach((c: any) => { counts[c.category] = (counts[c.category] || 0) + 1; });
console.log('Cases by category:');
Object.entries(counts).sort((a,b) => b[1]-a[1]).forEach(([cat, count]) => console.log(`  ${cat}: ${count}`));