import * as fs from 'fs';
import * as path from 'path';

function c(id: string, title: string, cat: string, ind: string, diff: string, prompt: string, ctx: string, facts: string[], hints: string[], calcs: string[], crit: string[]) {
  return { id, title, category: cat, industry: ind, difficulty: diff, prompt, context: ctx, keyFacts: facts, frameworkHints: hints, expectedCalculations: calcs, successCriteria: crit };
}

const moreCases: any[] = [
  // DIGITAL TRANSFORMATION (18 more to reach 20+)
  c('dt-07','Telecom 5G Digital Services','Digital Transformation','Telecommunications','Expert',
    'A telecom operator ($25B revenue) is launching 5G and wants to build a $5B digital services business on top of the network. Currently 90% of revenue is from connectivity.',
    '300M subscribers, 5G rolling out in 20 markets. Connectivity ARPU declining 5% annually. Digital services opportunity: enterprise IoT, edge computing, private networks, consumer AR/VR.',
    ['Revenue: $25B (90% connectivity)','Subscribers: 300M','5G coverage: 20 markets','ARPU: declining 5% annually','Digital services today: $2.5B (10% of revenue)','Target: $5B digital services in 5 years','Enterprise segment: 50K business customers','Network capex: $4B annually','Competitors: AT&T (Warner), T-Mobile (Magenta)','Technology gap: no cloud-native platform','Talent: 500 digital engineers (need 5,000)'],
    ['5G digital services portfolio design (B2B, B2C, B2B2X)','Cloud-native platform and API strategy','Enterprise IoT and private 5G network offerings','Consumer digital services (AR/VR, gaming, health)','Organization transformation: digital business unit'],
    ['Digital services revenue: $2.5B to $5B in 5 years','ARPU stabilization through digital upsell','Enterprise digital revenue growth','Platform economics and margin improvement','Organization and talent transformation investment'],
    ['5G digital services strategy','Platform and technology architecture','Enterprise and consumer offering design','Organization and capability transformation','Financial model and investment case']),
  c('dt-08','Manufacturing Industry 4.0 Rollout','Digital Transformation','Manufacturing','Hard',
    'A manufacturer ($12B revenue, 30 plants) wants to implement Industry 4.0 across all facilities. Currently: 2 plants are smart factories, rest are traditional.',
    '30 plants in 12 countries. Only 2 have IoT, digital twins, and AI. Current OEE: 65% (benchmark 85%). Annual maintenance cost: $600M.',
    ['Revenue: $12B','Plants: 30 (12 countries)','Smart factory count: 2','OEE: 65% (benchmark 85%)','Maintenance cost: $600M','Quality defect rate: 2.5% (benchmark 0.5%)','Downtime: 15% (benchmark 5%)','Workers: 25,000 across all plants','IT/OT systems: fragmented, no standardization','Digital maturity: Level 1-2 (of 5)','Investment available: $500M over 3 years','Competitor: Siemens (14 smart factories)'],
    ['Digital maturity assessment and roadmap by plant','IoT platform selection and deployment','Digital twin implementation strategy','AI/ML use cases: predictive quality, maintenance, scheduling','Worker upskilling and change management'],
    ['OEE improvement: 65% to 80% across all plants','Quality defect reduction: 2.5% to 0.8%','Maintenance cost reduction: $600M to $400M','Digital skills training: 25,000 workers','Payback period for $500M investment'],
    ['Industry 4.0 transformation strategy','Plant-by-plant implementation roadmap','Technology platform and architecture','Workforce transformation plan','Financial model with 3-year payback target']),
  c('dt-09','Insurance Telematics Platform','Digital Transformation','Insurance','Medium',
    'An auto insurer ($8B GWP) wants to launch a telematics-based usage insurance product. Currently: traditional underwriting, no real-time driving data.',
    '2M policyholders. Loss ratio: 72% (benchmark 65%). No driving behavior data. Competitors: Progressive Snapshot, GEICO DriveSafe.',
    ['GWP: $8B','Policyholders: 2M','Loss ratio: 72% (benchmark 65%)','Telematics adoption: 0% (benchmark 20%)','Target loss ratio: 65%','Competitor penetration: 20-30% of policies','Customer satisfaction: 72/100','Mobile app users: 40% (800K)','Data: no real-time driving data','Pricing model: demographic only','Regulatory: telematics approved in 45 states'],
    ['Telematics data collection (OBD device, mobile app)','Risk scoring model using driving behavior','Usage-based insurance product design','Customer acquisition and opt-in strategy','Privacy and regulatory compliance framework'],
    ['Loss ratio reduction from 72% to 65% = $560M savings','Telematics adoption: 0% to 30% of book','Customer retention improvement from personalized pricing','New customer acquisition from competitive pricing','Data monetization and partnership opportunities'],
    ['Telematics and usage-based insurance strategy','Data collection and risk modeling platform','Product design and pricing innovation','Customer acquisition and retention plan','Financial model and ROI analysis']),
  c('dt-10','Media Company Direct-to-Consumer Pivot','Digital Transformation','Media / Entertainment','Hard',
    'A traditional media company ($5B revenue: 70% broadcast, 30% digital) wants to flip to 30% broadcast, 70% digital in 3 years. Digital subscribers: 2M (need 15M).',
    'Broadcast TV networks, 200M reach. Digital: streaming with 2M subscribers ($5/month). Need to reach 15M subscribers at $12/month to offset broadcast decline.',
    ['Revenue: $5B (70% broadcast, 30% digital)','Digital subscribers: 2M (need 15M)','Streaming price: $5/month (need $12)','Broadcast reach: 200M households','Content spend: $2B annually','Digital content: 10% of budget (need 40%)','Ad revenue declining: 8% annually in broadcast','Competitors: Netflix (250M), Disney+ (150M), Peacock','Churn rate: 8% monthly (benchmark 5%)','Tech platform: licensed, not owned','Customer acquisition cost: $50 per subscriber'],
    ['Content strategy for streaming-first (originals, library)','Direct-to-consumer platform build vs license','Pricing and bundling strategy (ad-free, ad-supported)','Distribution and partnership strategy','Organization from broadcast to digital-first culture'],
    ['Digital subscribers: 2M to 15M in 3 years','Digital revenue: $1.5B to $3.5B','Content cost reallocation: 10% to 40% digital','Customer acquisition: 13M new subscribers at $50 CAC','Total investment: $1.5B over 3 years'],
    ['Direct-to-consumer transformation strategy','Content and programming strategy','Platform and technology roadmap','Organization and culture transformation','Financial model with subscriber growth projections']),
  c('dt-11','Logistics Real-Time Visibility Platform','Digital Transformation','Logistics / Supply Chain','Medium',
    'A third-party logistics provider ($10B revenue) wants to build a real-time visibility platform for 50K shippers. Currently: batch tracking, no real-time data.',
    '50,000 shippers, 2M shipments/month. Current tracking: batch updates every 4 hours. Customer complaints: 35% cite visibility as top issue.',
    ['Revenue: $10B','Shippers: 50,000','Shipments: 2M/month','Current tracking: batch updates every 4h','Customer complaints: 35% cite visibility','Customer churn: 12% annually','Competitor: project44, FourKites (real-time)','Data: GPS from 30% of fleet, nothing from carriers','Platform: legacy TMS, no API layer','Investment available: $100M','Target: real-time visibility for 90% of shipments'],
    ['Real-time visibility platform architecture','IoT and GPS data collection from multiple sources','Carrier onboarding and data integration','Customer-facing dashboard and API','Analytics: ETA prediction, exception management'],
    ['Visibility: batch to real-time for 90% of shipments','Customer churn reduction from 12% to 5%','Revenue uplift from premium visibility services','Operational efficiency from exception management','Customer satisfaction improvement from 65 to 85 NPS'],
    ['Real-time visibility platform strategy','Data collection and carrier integration','Customer experience and analytics platform','Implementation roadmap','Financial model and ROI analysis']),
  c('dt-12','Healthcare Patient Portal Overhaul','Digital Transformation','Healthcare','Medium',
    'A health system ($6B revenue, 30 hospitals, 500 clinics) has an outdated patient portal with 15% adoption. They want to build a modern digital health platform with 60% adoption.',
    '30 hospitals, 500 clinics, 3M patients. Current portal: basic, fragmented (3 different systems). Mobile app: none. Telehealth: 5% of visits.',
    ['Revenue: $6B','Hospitals: 30','Clinics: 500','Patients: 3M','Portal adoption: 15% (target 60%)','Current portal: basic, 3 fragmented systems','Mobile app: none','Telehealth: 5% of visits','Patient satisfaction with digital: 25th percentile','Cost per patient interaction: $15 (digital $2)','Competitors: Epic MyChart, Cerner Patient Portal','Regulatory: ONC interoperability rules'],
    ['Unified patient portal with single sign-on','Mobile-first design with patient engagement features','Telehealth and virtual care platform','Integration with EHRs (Epic, Cerner, Meditech)','Patient engagement: messaging, scheduling, records'],
    ['Portal adoption: 15% to 60%','Cost per interaction: $15 to $5 (digital shift)','Patient satisfaction improvement from 25th to 70th percentile','Revenue from telehealth expansion','Operational efficiency from self-service'],
    ['Digital health platform strategy','Portal and mobile app design','Integration and interoperability roadmap','Patient adoption and engagement plan','Financial model and implementation timeline']),
  c('dt-13','Energy Company Digital Field Operations','Digital Transformation','Energy / Utilities','Hard',
    'An oil and gas company ($20B revenue, 500 field sites) is deploying digital tools for 10,000 field workers. Currently: paper-based, 2-hour average response time to incidents.',
    '500 field sites, 10,000 field workers. Paper-based work orders, manual safety inspections, no real-time monitoring. Incident response: 2 hours average. Target: 15 minutes.',
    ['Revenue: $20B','Field sites: 500','Field workers: 10,000','Current response time: 2 hours (target 15 min)','Work orders: paper-based','Safety inspections: manual, quarterly','Equipment downtime: 12% ($2.4B annual cost)','Maintenance cost: $1.5B annually','Incident rate: 2.5 per 100 workers (benchmark 1.0)','Digital maturity: Level 1','IT budget: $500M (10% for digital)'],
    ['Mobile field worker platform (work orders, inspections)','IoT sensors for equipment monitoring','Real-time safety monitoring and incident response','Digital twin of critical assets','AR/VR for remote expert assistance'],
    ['Response time: 2 hours to 15 minutes','Equipment downtime: 12% to 5% = $1.4B savings','Maintenance cost reduction: $1.5B to $1B','Safety incident rate reduction: 2.5 to 1.0','Field worker productivity improvement: 25%'],
    ['Digital field operations strategy','Mobile and IoT platform architecture','Safety and incident response digitization','Implementation across 500 sites','Financial model with $1.4B downtime savings']),
  c('dt-14','Banking Core Modernization','Digital Transformation','Banking / Financial Services','Expert',
    'A regional bank ($50B assets) is running on a 30-year-old core banking system. They want to modernize to compete with fintech challengers. Current: 40% digital adoption, high cost-to-serve.',
    'Core system: 30 years old, COBOL-based, 3rd party vendor. Cost to maintain: $200M/year. New product launch: 6 months (benchmark 2 weeks). Digital adoption: 40%.',
    ['Assets: $50B','Core system age: 30 years (COBOL)','Maintenance cost: $200M/year','New product launch: 6 months (benchmark 2 weeks)','Digital adoption: 40%','Branches: 200','Customers: 2M','Cost-to-income ratio: 65% (benchmark 45%)','Digital competitors: 5 neobanks in market','Regulatory requirements: strict compliance','Data: locked in legacy systems, no real-time','Staff: 5,000 (30% in IT)'],
    ['Core banking modernization strategy (replace, re-platform, or wrap)','Cloud migration and API-first architecture','Digital product factory for rapid launch','Data platform for real-time analytics','Branch and workforce transformation'],
    ['Maintenance cost: $200M to $50M','New product launch: 6 months to 2 weeks','Cost-to-income ratio: 65% to 50%','Digital adoption: 40% to 80%','Customer growth: 2M to 3M from digital channels'],
    ['Core modernization strategy with risk assessment','Cloud and API architecture','Digital product and platform strategy','Branch and workforce transformation','Financial model with $150M annual savings']),
  c('dt-15','Retail Media Network Launch','Digital Transformation','Retail / Advertising','Medium',
    'A grocery chain ($30B revenue, 1,000 stores) wants to build a retail media network leveraging its loyalty data (15M members). Target: $500M in ad revenue in 3 years.',
    '1,000 stores, 15M loyalty members, $30B revenue. Current: no media business. Competitor: Walmart Connect ($2B+), Kroger Precision Marketing.',
    ['Revenue: $30B (grocery)','Stores: 1,000','Loyalty members: 15M','Competitor: Walmart Connect $2B+, Kroger $1B+','Target: $500M ad revenue in 3 years','Data: purchase history, demographics, store visits','Current data monetization: $0','Digital ads market: growing 25% annually','Advertiser demand: 200 CPG brands as partners','Technology: basic loyalty platform, no DSP','Privacy: first-party data advantage (cookie deprecation)'],
    ['Retail media platform build (DSP, ad server)','Data clean room for advertiser analytics','Advertiser sales team and go-to-market','Measurement and attribution framework','Privacy and compliance framework'],
    ['Ad revenue: $0 to $500M in 3 years','Advertiser count: 0 to 200 brands','Data-driven advertising ROAS vs traditional','Loyalty member engagement improvement','Gross margin on media: 70%+'],
    ['Retail media network strategy','Platform and data architecture','Advertiser acquisition and sales strategy','Measurement and attribution platform','Financial model with $500M revenue target']),
  c('dt-16','Education Digital Learning Platform','Digital Transformation','Education / EdTech','Easy',
    'A university ($2B revenue, 40K students) wants to build a hybrid digital learning platform. Currently: 90% in-person, limited LMS usage, no online degree programs.',
    '40,000 students, 2,000 faculty, 200 programs. LMS adoption: 30% of courses. Online programs: 0. Competitor: Arizona State (online 70K students).',
    ['Revenue: $2B (90% in-person tuition)','Students: 40,000','Faculty: 2,000','Programs: 200','LMS adoption: 30%','Online programs: 0 (target: 50)','Competitor: ASU online 70K students','Market: online higher ed $100B and growing 15%','Technology: basic LMS (Canvas), no video platform','Student satisfaction with tech: 40/100','Digital skills gap: 60% of faculty need training'],
    ['Hybrid learning platform design (LMS, video, assessment)','Online program development (50 programs in 3 years)','Faculty digital training program','Student engagement and retention tools','Marketing and student acquisition for online'],
    ['Online enrollment: 0 to 20,000 students in 3 years','Online revenue: $0 to $400M','Faculty digital proficiency: 40% to 90%','Student satisfaction with tech: 40 to 80/100','Cost per online student: 50% of in-person'],
    ['Digital learning transformation strategy','Platform and technology architecture','Online program portfolio design','Faculty training and adoption plan','Financial model with $400M online revenue target']),
  c('dt-17','Insurance Claims AI Automation','Digital Transformation','Insurance','Hard',
    'A property and casualty insurer ($12B GWP) processes 1M claims/year with 40% straight-through processing rate. They want to achieve 80% STP using AI.',
    '1M claims/year, 40% STP (benchmark 80%). Average claims cycle: 30 days (benchmark 7). Claims cost: $8B annually. Leakage: 15% (benchmark 5%).',
    ['GWP: $12B','Claims volume: 1M/year','STP rate: 40% (benchmark 80%)','Average claims cycle: 30 days (benchmark 7)','Claims cost: $8B annually','Claims leakage: 15% ($1.2B) vs benchmark 5%','Customer satisfaction: 55/100','Claims staff: 3,000','Fraud detection: manual review of 10%','Technology: legacy claims system, basic rules engine','Competitor: Lemonade (AI claims in 3 seconds)'],
    ['AI/ML claims triage and routing','Computer vision for damage assessment (auto, property)','NLP for claims intake and documentation','Fraud detection and anomaly scoring','Straight-through processing engine'],
    ['STP rate: 40% to 80%','Claims cycle time: 30 days to 7 days','Claims leakage: 15% to 5% = $800M savings','Customer satisfaction: 55 to 80/100','Claims staff redeployment: 1,500 to value-added roles'],
    ['AI claims automation strategy','Computer vision and NLP implementation','STP engine and workflow redesign','Fraud detection platform','Financial model with $800M leakage reduction']),
  c('dt-18','Agricultural Precision Farming Platform','Digital Transformation','Agriculture','Medium',
    'A large agribusiness ($8B revenue) wants to build a precision farming digital platform for 10,000 partner farmers. Currently: no digital tools, traditional farming practices.',
    '10,000 partner farmers, 20M acres. Crop yield: 15% below optimal. Input costs: $3B. Digital tools: none. Competitor: John Deere Operations Center.',
    ['Revenue: $8B','Partner farmers: 10,000','Acres: 20M','Yield gap: 15% below optimal','Input costs: $3B (seeds, fertilizer, chemicals)','Digital tools: none','Competitor: John Deere, Climate Corp','Market opportunity: precision ag $12B by 2028','Data: soil tests (quarterly), no real-time','Climate risk: increasing variability','Farmer tech adoption: low (average age 55)'],
    ['Precision farming platform (soil, weather, satellite)','AI/ML yield optimization recommendations','Input optimization (seeds, fertilizer, chemicals)','Farm management software and mobile app','Data partnerships (equipment OEMs, weather services)'],
    ['Yield improvement: 15% gap to 5% = $1.2B value','Input cost reduction: 10% = $300M savings','Platform revenue: $100M/year from 10,000 farmers','Carbon credit monetization potential','Data-driven agronomy advisory services'],
    ['Precision farming platform strategy','AI/ML and data analytics capabilities','Farmer adoption and engagement plan','Partnership and ecosystem strategy','Financial model with $1.5B total value creation']),
  c('dt-19','Pharma Digital Clinical Trials','Digital Transformation','Pharmaceuticals','Expert',
    'A pharmaceutical company ($25B revenue) wants to digitize clinical trials. Currently: 90% site-based, 50% of trials delayed, $2B annual trial cost.',
    '150 active trials, 50,000 patients. 90% site-based (target 50% decentralized). Trial delays: 50% (cost $100M each). Patient recruitment: 30% fail to meet targets.',
    ['Revenue: $25B','Active trials: 150','Patients: 50,000','Site-based: 90% (target 50% decentralized)','Trial delays: 50% ($100M cost each)','Recruitment failures: 30% of trials','Annual trial cost: $2B','Patient dropout: 25%','Data: paper CRFs in 40% of sites','Regulatory: FDA accepts DHT data','Competitor: Medidata, Oracle Health Sciences'],
    ['Decentralized clinical trial (DCT) platform','Wearable and remote patient monitoring','AI-powered patient recruitment and matching','Electronic data capture and real-time analytics','Regulatory strategy for digital endpoints'],
    ['Trial timeline reduction: 50% delay to 20% delay','Patient recruitment improvement: 30% failure to 10%','Patient dropout reduction: 25% to 10%','Cost per trial reduction: 20%','Time-to-market improvement: 6 months faster'],
    ['Digital clinical trials transformation strategy','DCT platform and wearable integration','Patient recruitment and retention platform','Regulatory and compliance framework','Financial model with $600M annual savings']),
  c('dt-20','Insurance Product Configuration Engine','Digital Transformation','Insurance','Medium',
    'A commercial insurer ($6B GWP) takes 9 months to launch new products. They want to build a no-code product configuration engine to launch in 2 weeks.',
    'Commercial lines: 50 products, 20 states. Current: 9 months per product launch. IT bottleneck: 80% of time spent on configuration vs innovation.',
    ['GWP: $6B','Products: 50 commercial lines','States: 20','Product launch time: 9 months (target 2 weeks)','IT bottleneck: 80% on configuration','Product changes: 200/year','Compliance changes: 50/year','Underwriter manual processes: 60%','Competitor: Socotra (cloud-native core)','Regulatory filing: 4-6 weeks per state','Customer demand: 40% want digital self-service'],
    ['No-code product configuration engine','Rate/rule management and versioning','Regulatory compliance automation','Underwriter workflow and decision engine','API-first architecture for distribution channels'],
    ['Product launch time: 9 months to 2 weeks','Product change implementation: 4 weeks to 1 day','IT time on configuration: 80% to 20%','Underwriter productivity: 40% improvement','Time-to-revenue for new products: 6x faster'],
    ['Product configuration engine architecture','No-code/low-code platform selection','Regulatory compliance automation','Underwriter workflow redesign','Financial model and implementation roadmap']),
  c('dt-21','Fashion Virtual Try-On Platform','Digital Transformation','Fashion / E-commerce','Medium',
    'A fashion retailer ($3B revenue, 20M online customers) has 30% return rate due to fit issues. They want to deploy AR virtual try-on to reduce returns by 40%.',
    '30% return rate (industry avg 20%). 20M online customers. Fit/size: #1 reason for returns (60%). AR technology: available but unproven at scale.',
    ['Revenue: $3B (online 40%)','Online customers: 20M','Return rate: 30% (industry avg 20%)','Fit/size issues: 60% of returns','Return processing cost: $150M/year','AR technology cost: $50M implementation','Size data: basic (S, M, L)','Body measurement data: none','Mobile traffic: 70% of visits','Conversion rate: 2.5%','Competitor: Warby Parker (virtual try-on), ASOS (Fit Assistant)'],
    ['AR virtual try-on for clothing and shoes','AI-powered size recommendation engine','Body measurement technology (phone camera)','Fit database from return data analytics','Integration with product pages and checkout'],
    ['Return rate reduction: 30% to 18% = $180M savings','Conversion rate improvement: 2.5% to 3.5%','Customer satisfaction with fit: 50% to 80%','Size data creation: 20M body measurements','AR engagement rate: 25% of visitors'],
    ['Virtual try-on technology strategy','AI size recommendation platform','Body measurement and fit analytics','Customer adoption and engagement plan','Financial model with $180M return savings']),
  c('dt-22','Banking AI-Powered Personalization','Digital Transformation','Banking / Financial Services','Medium',
    'A retail bank ($80B assets, 5M customers) wants to deliver personalized financial advice at scale. Currently: generic product pushes, 2% cross-sell rate.',
    '5M customers, 8M accounts. Cross-sell rate: 2% (benchmark 15%). Customer satisfaction: 60/100. Digital engagement: 45%. Personalization: none.',
    ['Assets: $80B','Customers: 5M','Accounts: 8M','Cross-sell rate: 2% (benchmark 15%)','Customer satisfaction: 60/100','Digital engagement: 45%','Personalization: none (generic product pushes)','Revenue per customer: $400 (benchmark $800)','NPS: 15 (benchmark 45)','Competitor: JPMorgan (personalized at scale)','Data: transaction history, demographics, behavior'],
    ['AI/ML customer segmentation and next-best-action','Personalized financial health scoring','Contextual product recommendations','Hyper-personalized communication (email, push, in-app)','Privacy and consent management framework'],
    ['Cross-sell rate: 2% to 15%','Revenue per customer: $400 to $800','Customer satisfaction: 60 to 80/100','NPS improvement: 15 to 45','Digital engagement: 45% to 75%'],
    ['AI personalization strategy','Customer data and segmentation platform','Next-best-action engine design','Personalization use cases and roadmap','Financial model with $2B revenue uplift']),
  c('dt-23','Supply Chain Control Tower','Digital Transformation','Supply Chain / Retail','Expert',
    'A consumer goods company ($15B revenue, 500 suppliers, 20 warehouses) has zero end-to-end supply chain visibility. They want to build a control tower for real-time visibility and predictive analytics.',
    '500 suppliers, 20 warehouses, 100 distribution points. Current: batch updates, 24-hour lag. Disruptions cost $500M annually in expedited shipping and lost sales.',
    ['Revenue: $15B','Suppliers: 500','Warehouses: 20','Distribution points: 100','Current visibility: batch (24h lag)','Disruption cost: $500M annually','Expedited shipping: $200M annually','Inventory excess: $1B above optimal','Demand forecast accuracy: 70%','Supply chain cost: 15% of revenue ($2.25B)','Competitor: Unilever (control tower), P&G (digital SC)'],
    ['Real-time supply chain visibility platform','Predictive disruption detection and alerts','Dynamic inventory rebalancing engine','Control tower operations and response protocols','Integration with 500 suppliers and 20 warehouses'],
    ['Expedited shipping reduction: $200M to $80M','Disruption cost reduction: $500M to $200M','Inventory optimization: $1B to $600M','Demand forecast accuracy: 70% to 90%','Response time to disruption: 24h to 2h'],
    ['Supply chain control tower strategy','Platform architecture and data integration','Predictive analytics and disruption management','Supplier and warehouse integration','Financial model with $820M annual savings']),
];

const jsonPath = path.join(__dirname, '../../data/generated-cases.json');
let existing: any[] = [];
try {
  existing = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
} catch(e) {}

const seen = new Set(existing.map(c => c.id));
const newCases = moreCases.filter(c => !seen.has(c.id));
const merged = [...existing, ...newCases];
fs.writeFileSync(jsonPath, JSON.stringify(merged, null, 0), 'utf-8');
console.log(`Added ${newCases.length} new cases. Total: ${merged.length}`);
const counts: Record<string, number> = {};
merged.forEach((c: any) => { counts[c.category] = (counts[c.category] || 0) + 1; });
console.log('Cases by category:');
Object.entries(counts).sort((a,b) => b[1]-a[1]).forEach(([cat, count]) => console.log(`  ${cat}: ${count}`));