import * as fs from 'fs';
import * as path from 'path';

function c(id: string, title: string, cat: string, ind: string, diff: string, prompt: string, ctx: string, facts: string[], hints: string[], calcs: string[], crit: string[]) {
  return { id, title, category: cat, industry: ind, difficulty: diff, prompt, context: ctx, keyFacts: facts, frameworkHints: hints, expectedCalculations: calcs, successCriteria: crit };
}

const moreCases: any[] = [
  // TURNAROUND / RESTRUCTURING (18 more to reach 20+)
  c('tr-07','Airline Fleet Restructuring','Turnaround / Restructuring','Aviation / Airlines','Expert',
    'An airline ($15B revenue) is losing $2B annually with an aging fleet, high fuel costs, and unprofitable routes. They need a complete turnaround to survive.',
    '200 aircraft (avg age 14 years, benchmark 8). Fuel cost: 35% of revenue (benchmark 25%). Load factor: 72% (benchmark 85%). Routes: 150 (40% unprofitable).',
    ['Revenue: $15B','Net loss: -$2B annually','Fleet: 200 aircraft (avg age 14 years, benchmark 8)','Fuel cost: 35% of revenue ($5.25B)','Load factor: 72% (benchmark 85%)','Routes: 150 (40% unprofitable = 60 routes)','Passengers: 50M/year','Employee count: 45,000 (need 30,000)','Debt: $12B','Cash: $1.5B (6 months runway)','Competitors: 5 major airlines, 3 LCCs','Labor cost: 30% of revenue (benchmark 25%)'],
    ['Fleet renewal strategy (retire old, order efficient aircraft)','Route profitability analysis and network optimization','Cost reduction: fuel hedging, maintenance optimization','Revenue management and yield improvement','Workforce restructuring: 15,000 positions','Debt restructuring with creditors'],
    ['Fleet fuel efficiency improvement: 35% to 25%','Route pruning: eliminate 60 unprofitable routes','Cost reduction: $3B over 2 years','Load factor improvement: 72% to 82%','Debt reduction from $12B to $8B'],
    ['Comprehensive airline turnaround strategy','Fleet and network optimization plan','Cost reduction and restructuring program','Revenue improvement and market positioning','Financial model and creditor negotiation plan']),
  c('tr-08','Retail Chain Store Closures and Rebrand','Turnaround / Restructuring','Retail','Hard',
    'A department store chain ($8B revenue, 400 stores) is losing $1B annually. 40% of stores are unprofitable. They need to close 150 stores, rebrand, and transform digitally.',
    '400 stores in malls (60%) and off-mall (40%). Revenue declining 10% annually. E-commerce: 8% of sales (benchmark 30%). Brand perception: dated.',
    ['Revenue: $8B (declining 10% annually)','Stores: 400 (150 to close)','Unprofitable stores: 40% (160 stores)','Net loss: -$1B annually','E-commerce: 8% of sales (benchmark 30%)','Mall concentration: 60%','Avg store size: 100K sq ft','Inventory: $3B (turns: 2x, benchmark 4x)','Lease obligations: $4B (avg 5 years)','Employee count: 30,000 (to reduce to 20,000)','Brand awareness: 60% (declining)','Competitor: Nordstrom (thriving), Sears (failed)'],
    ['Store closure strategy (which 150, exit costs, timeline)','Brand repositioning and marketing relaunch','E-commerce acceleration (from 8% to 30%)','Inventory reduction and supply chain optimization','Workforce restructuring and severance planning','Lease renegotiation and exit strategy'],
    ['Store closures: 150 stores saving $600M annually','Revenue loss from closures: $1.5B','Digital revenue: 8% to 30% = $2.4B','Inventory reduction: $3B to $1.5B','Net improvement: break-even in 2 years'],
    ['Turnaround strategy with store closure plan','Brand repositioning and digital transformation','Workforce and lease restructuring','E-commerce acceleration strategy','Financial model with break-even timeline']),
  c('tr-09','Telecom Subscriber Loss Crisis','Turnaround / Restructuring','Telecommunications','Hard',
    'A telecom operator ($12B revenue) is losing 500K subscribers quarterly to competitors. Net Promoter Score: -20. Network quality complaints: 40% of calls.',
    'Subscribers declining from 20M to 18M. Churn rate: 3% monthly (benchmark 1.5%). ARPU: $45 (benchmark $55). Network: 60% 4G coverage (benchmark 95% 5G).',
    ['Revenue: $12B (declining)','Subscribers: 18M (losing 500K/quarter)','Churn rate: 3% monthly (benchmark 1.5%)','ARPU: $45 (benchmark $55)','NPS: -20 (benchmark +30)','Network complaints: 40% of calls','4G coverage: 60% (competitors 95% 5G)','Net loss: -$500M annually','Market share: 15% (was 25%)','Fiber coverage: 20%','Competitors: 3 operators, 2 with 5G','Workforce: 8,000 (20% overstaffed)'],
    ['Network quality rapid improvement plan','Customer retention and win-back program','Competitive pricing and value proposition','Digital customer experience overhaul','Operational cost restructuring'],
    ['Subscriber loss: 500K/quarter to net positive','Churn reduction: 3% to 1.5%','ARPU improvement: $45 to $55','NPS improvement: -20 to +20','Return to profitability in 18 months'],
    ['Telecom turnaround strategy','Network improvement and 5G deployment','Customer retention and acquisition plan','Pricing and product restructuring','Financial model with subscriber recovery projections']),
  c('tr-10','Auto Parts Manufacturer Electric Transition','Turnaround / Restructuring','Automotive / Manufacturing','Expert',
    'An auto parts manufacturer ($6B revenue) makes 80% ICE components. EV adoption is threatening their core business. They need to pivot to EV components while managing ICE decline.',
    '80% revenue from ICE components (declining 15% annually). 20% from electronics. Need to become 50% EV-compatible in 3 years. 10 factories, 8 designed for ICE.',
    ['Revenue: $6B (80% ICE, 20% electronics)','ICE revenue declining: 15% annually','EV trend: 40% of new cars by 2028','Factories: 10 (8 ICE-specific)','Workers: 15,000 (5,000 ICE-specific skills)','Customer base: 20 OEMs (15 ICE, 5 EV)','R&D spend: $200M (80% ICE, need 80% EV)','Competitor: Bosch (60% EV-ready), Continental','Technology gap: no battery, motor, or power electronics','Investment needed: $2B for EV transition','Timeline: 3 years to be 50% EV-compatible'],
    ['EV component strategy (battery, motor, power electronics, thermal)','Factory retooling and automation','Customer win-back from ICE to EV programs','R&D reallocation and talent acquisition','Strategic partnerships or acquisitions for EV technology'],
    ['EV revenue: 20% to 50% in 3 years','ICE decline management: minimize revenue loss','Factory conversion: 8 ICE to 5 EV-ready','R&D reallocation: 80% EV by Year 1','Customer retention: keep 15 ICE accounts while winning EV business'],
    ['EV transition turnaround strategy','Factory and capability transformation plan','Customer and market strategy','Talent and organization redesign','Financial model with $2B investment and 5-year ROI']),
  c('tr-11','Hospital Network Financial Recovery','Turnaround / Restructuring','Healthcare / Hospital Network','Hard',
    'A hospital network ($4B revenue, 8 hospitals) is hemorrhaging $400M annually. Three rural hospitals are unprofitable, payer mix is deteriorating, and physician turnover is 25%.',
    '8 hospitals: 5 urban (profitable), 3 rural (losing $200M). Payer mix: 40% Medicare/Medicaid (reimburses 60% of cost). Physician turnover: 25%. ER diversion rate: 15%.',
    ['Revenue: $4B','Net loss: -$400M annually','Hospitals: 8 (5 urban profitable, 3 rural losing $200M)','Payer mix: 40% government (Medicare/Medicaid)','Physician turnover: 25% (benchmark 10%)','ER diversion rate: 15%','Bed occupancy: 55% (benchmark 80%)','Length of stay: 5.5 days (benchmark 4.5)','IT systems: 4 different EHRs','Malpractice insurance: rising 20% annually','Community: rural hospitals are sole providers'],
    ['Service line rationalization (what to keep, what to close)','Payer strategy: value-based care contracts','Physician recruitment and retention program','Operational efficiency: LEAN Six Sigma','Rural hospital transformation (critical access, telemedicine)','IT consolidation and interoperability'],
    ['Net loss reduction: -$400M to break-even','Rural hospital strategy: close, convert, or restructure','Physician turnover: 25% to 10%','Bed occupancy: 55% to 75%','Length of stay: 5.5 to 4.5 days'],
    ['Hospital network turnaround strategy','Service line and rural hospital restructuring','Payer and revenue cycle optimization','Physician retention and operational efficiency','Financial model with break-even in 18 months']),
  c('tr-12','Consumer Packaged Goods Brand Revival','Turnaround / Restructuring','Consumer Packaged Goods','Medium',
    'A legacy CPG brand ($5B revenue) has lost 30% market share in 5 years to DTC competitors. Brand perception is outdated. They need to revitalize while maintaining core customers.',
    '50-year-old brand, $5B revenue (was $7B). Market share declining 6% annually. DTC competitors growing 40% annually. Core customer aging (avg 55, target 35).',
    ['Revenue: $5B (was $7B, declining 6% annually)','Market share: 12% (was 18%)','DTC competitors: growing 40% annually','Core customer avg age: 55 (target 35)','Brand awareness: 80% (but low relevance for <40)','Distribution: 90% retail (benchmark: 60% retail, 40% DTC)','Digital: 5% of sales (benchmark 25%)','Innovation: 1 new product/year (benchmark 10)','Marketing spend: $500M (80% TV, 20% digital)','Competitor: 20+ DTC brands collectively taking 15% share','E-commerce: Amazon #1 seller, no DTC presence'],
    ['Brand repositioning for younger demographics','DTC channel launch and e-commerce acceleration','Product innovation pipeline (10 launches/year)','Marketing mix shift: TV to digital/social/influencer','Retail partner strategy evolution'],
    ['Revenue stabilization: stop 6% annual decline','DTC revenue: 0% to 25% of sales ($1.25B)','Digital marketing ROI: 3x vs traditional','New customer acquisition: 1M under-40 customers/year','Market share recovery: 12% to 15%'],
    ['Brand turnaround and revitalization strategy','DTC and digital transformation plan','Product innovation pipeline','Marketing and channel strategy','Financial model with market share recovery targets']),
  c('tr-13','Restaurant Chain Operational Overhaul','Turnaround / Restructuring','Food & Beverage / Restaurants','Easy',
    'A fast-casual chain ($2B revenue, 800 locations) is losing market share. Food costs: 35% (benchmark 28%). Wait time: 12 minutes (benchmark 5). Customer satisfaction: 3.2/5.',
    '800 locations, avg revenue $2.5M/location. Food costs 35%, labor 30%, rent 15%. Profit margin: -2% (benchmark 8%). Drive-through: 40% of orders, 12 min avg wait.',
    ['Revenue: $2B (800 locations)','Avg revenue per location: $2.5M','Food cost: 35% (benchmark 28%)','Labor cost: 30% (benchmark 25%)','Rent: 15% (benchmark 10%)','Profit margin: -2% (benchmark 8%)','Drive-through wait: 12 min (benchmark 5)','Customer satisfaction: 3.2/5','Digital orders: 15% (benchmark 40%)','Delivery: 10% (through 3rd party, 30% commission)','Employee turnover: 120% annually'],
    ['Menu engineering for food cost optimization','Kitchen workflow and speed improvement','Digital ordering and drive-through technology','Labor scheduling optimization','Delivery channel strategy (reduce 3rd party dependence)'],
    ['Food cost: 35% to 28% = $140M savings','Labor cost: 30% to 25% = $100M savings','Drive-through time: 12 min to 5 min','Digital orders: 15% to 40%','Net margin improvement: -2% to 8% = $200M profit'],
    ['Restaurant turnaround strategy','Menu and food cost optimization','Digital and drive-through improvement','Labor and operational efficiency','Financial model with margin recovery plan']),
  c('tr-14','Industrial Conglomerate Divestiture Strategy','Turnaround / Restructuring','Industrial / Conglomerate','Expert',
    'A conglomerate ($30B revenue, 5 business units) is trading at a 30% conglomerate discount. Shareholders want breakup. They need to decide: divest, spin-off, or restructure.',
    '5 units: chemicals ($10B, 8% margin), packaging ($8B, 12%), automation ($6B, 15%), services ($4B, 5%), real estate ($2B, 20%). Total market cap: $15B (should be $22B).',
    ['Revenue: $30B (5 business units)','Market cap: $15B (conglomerate discount: 30%)','Units: Chemicals ($10B, 8%), Packaging ($8B, 12%), Automation ($6B, 15%), Services ($4B, 5%), Real estate ($2B, 20%)','Debt: $10B','Overhead: $1.5B corporate (5% of revenue)','Synergies: $500M between units','Board pressure: activist investor demanding breakup','CEO tenure: 2 years (turnaround mandate)','Regulatory: antitrust for some divestitures','Timeline: 18 months for transformation'],
    ['Portfolio analysis: hold, divest, or spin-off each unit','Valuation analysis: sum-of-parts vs conglomerate','Separation costs and dis-synergies','Management team reallocation','Shareholder communication and governance reform'],
    ['Conglomerate discount elimination: $15B to $22B market cap','Divestiture proceeds from services and real estate: $6B','Corporate overhead reduction: $1.5B to $500M','Debt reduction: $10B to $6B','Focus: 3 core units with 10%+ margins'],
    ['Portfolio restructuring strategy','Divestiture and spin-off recommendations','Valuation and financial modeling','Governance and shareholder value plan','Execution roadmap with 18-month timeline']),
  c('tr-15','Banking NPL Crisis Resolution','Turnaround / Restructuring','Banking / Financial Services','Expert',
    'A bank ($30B assets) has 15% non-performing loans (NPLs) from a real estate portfolio collapse. They need to clean up the balance sheet while maintaining operations.',
    'NPL ratio: 15% ($4.5B). Provision for credit losses: $2B. Capital adequacy: 8% (minimum 10.5%). Liquidity ratio: 90% (minimum 100%).',
    ['Assets: $30B','NPLs: 15% ($4.5B, mostly real estate)','Provision for credit losses: $2B','Capital adequacy: 8% (minimum 10.5%)','Liquidity ratio: 90% (minimum 100%)','Deposits: $20B (30% wholesale funded)','Real estate exposure: 40% of loan book ($12B)','NPL resolution rate: 20% (benchmark 60%)','Legal proceedings: 500 cases pending','NII margin: 3.2% (benchmark 3.5%)','Regulatory: under supervision, remediation plan required'],
    ['NPL resolution strategy (restructure, provision, sell, or write-off)','Real estate asset management and recovery','Capital raising strategy (equity, sub-debt, asset sales)','Deposit base strengthening','Regulatory compliance and remediation','Asset-liability management'],
    ['NPL ratio: 15% to 5% in 3 years','Capital adequacy: 8% to 12%','Liquidity ratio: 90% to 110%','NPL resolution: recover 50% of $4.5B ($2.25B)','Cost of resolution: $1B in provisions and write-offs'],
    ['NPL resolution and balance sheet cleanup strategy','Capital strengthening and regulatory compliance','Asset management and recovery plan','Deposit and funding strategy','Financial model with 3-year NPL reduction roadmap']),
  c('tr-16','Tech Startup Profitability Pivot','Turnaround / Restructuring','Technology / SaaS','Medium',
    'A SaaS startup ($200M ARR) is burning $150M/year. Growth has slowed to 20% (was 80%). They need to reach profitability within 18 months or face shutdown.',
    'ARR: $200M (growing 20%, was 80%). Burn: $150M/year. Cash: $100M (8 months runway). Customers: 5,000. Churn: 15% (benchmark 5%). CAC: $50K (LTV: $100K).',
    ['ARR: $200M (growth slowing: 80% to 20%)','Burn rate: $150M/year','Cash: $100M (8 months runway)','Customers: 5,000','Churn rate: 15% (benchmark 5%)','CAC: $50K (LTV: $100K, LTV/CAC = 2x, benchmark 5x)','Employees: 2,000 (target: 1,200)','Gross margin: 60% (benchmark 80%)','NDR: 90% (benchmark 120%)','Pricing: $40K ACV','Competitors: 10 well-funded alternatives'],
    ['Aggressive cost reduction to extend runway','Churn reduction and customer success overhaul','Pricing and packaging optimization','Gross margin improvement (cloud cost optimization)','Revenue focus: land-and-expand strategy'],
    ['Burn rate reduction: $150M to $30M/month','Churn reduction: 15% to 5%','Gross margin: 60% to 80%','LTV/CAC: 2x to 5x','Path to profitability: EBITDA positive in 18 months'],
    ['Startup turnaround and profitability pivot strategy','Cost reduction and runway extension plan','Customer retention and revenue optimization','Pricing and unit economics improvement','Financial model with 18-month profitability path']),
  c('tr-17','Pharmaceutical Patent Cliff Response','Turnaround / Restructuring','Pharmaceuticals','Hard',
    'A pharma company ($20B revenue) faces a $8B revenue cliff when its top drug loses patent exclusivity in 2 years. Pipeline is weak. They need to bridge the gap.',
    'Top drug: $8B revenue (40% of total), patent cliff in 2 years. Pipeline: 3 late-stage drugs, combined peak sales $2B. Generic competition expected to capture 80% within 12 months.',
    ['Revenue: $20B ($8B from top drug, 40%)','Patent cliff: 2 years','Generic erosion: 80% within 12 months ($6.4B loss)','Pipeline: 3 late-stage drugs (peak sales $2B combined)','R&D spend: $3B (15% of revenue)','Cash: $5B','M&A budget: $10B available','Workforce: 30,000','Sales force: 5,000 (focused on top drug)','Regulatory: 2 ANDAs filed by generics companies','Competitor: 3 companies with generic versions ready'],
    ['Patent cliff mitigation (authorized generics, litigation, settlements)','Pipeline acceleration (fast-track approvals, label expansion)','M&A for pipeline acquisition (buy revenue to bridge gap)','Cost restructuring for post-cliff revenue level','Lifecycle management (new formulations, combinations)'],
    ['Revenue gap: $8B loss, need to cover $4B+ through new sources','Pipeline acceleration: bring 1 drug forward 6 months','M&A: acquire $2B+ revenue product','Cost restructuring: reduce $3B to match post-cliff revenue','Cash deployment: optimal mix of M&A vs R&D'],
    ['Patent cliff response strategy','M&A and pipeline acceleration plan','Cost and revenue restructuring','Lifecycle management and legal strategy','Financial model with revenue bridge plan']),
  c('tr-18','Logistics Company Union Restructuring','Turnaround / Restructuring','Logistics / Transportation','Hard',
    'A trucking company ($3B revenue) has a unionized workforce with restrictive work rules. Labor costs are 45% of revenue (benchmark 30%). They need to renegotiate or restructure.',
    'Union workforce: 10,000 drivers, 2,000 dock workers. Labor cost: 45% of revenue ($1.35B). Work rules: no cross-training, strict seniority, 23% absenteeism. Non-union competitors: 30% labor cost.',
    ['Revenue: $3B','Labor cost: 45% ($1.35B, benchmark 30%)','Union workers: 12,000 (10K drivers, 2K dock)','Work rules: no cross-training, strict seniority','Absenteeism: 23% (benchmark 5%)','Contract expiration: 8 months','Non-union competitors: 30% labor cost','Profit margin: -1% (benchmark 8%)','Safety record: above industry average','Customer satisfaction: declining','Strike risk: high if negotiations fail'],
    ['Union contract renegotiation strategy','Operational flexibility improvements','Technology investment to reduce labor dependency','Workforce transition planning (if strike)','Non-union facility expansion strategy'],
    ['Labor cost: 45% to 35% = $300M savings','Absenteeism: 23% to 8%','Productivity improvement: 20%','Strike risk mitigation and contingency plan','Margin improvement: -1% to 8% = $270M profit'],
    ['Labor restructuring and union negotiation strategy','Operational flexibility and technology plan','Contingency and strike preparedness','Non-union expansion strategy','Financial model with $300M labor cost reduction']),
  c('tr-19','Education Institution Revenue Diversification','Turnaround / Restructuring','Education / Higher Education','Medium',
    'A university ($800M revenue) is 90% dependent on tuition. Enrollment is declining 5% annually. They need to diversify to survive.',
    'Enrollment: 15,000 (was 20,000, declining 5%/year). Tuition: 90% of revenue. Endowment: $500M. Deferred maintenance: $200M. Faculty: 800.',
    ['Revenue: $800M (90% tuition = $720M)','Enrollment: 15,000 (declining 5%/year, was 20K)','Tuition dependence: 90%','Endowment: $500M','Deferred maintenance: $200M','Faculty: 800 (20% nearing retirement)','Student satisfaction: 60/100','Alumni giving rate: 15% (benchmark 25%)','Online programs: minimal','Research funding: $50M (benchmark $150M)','Competitor: 10 similar institutions in region'],
    ['Revenue diversification: corporate training, online, research','Enrollment recovery through new programs and marketing','Alumni engagement and giving improvement','Endowment growth strategy','Cost structure optimization'],
    ['Tuition dependence: 90% to 60% in 5 years','New revenue streams: $200M from corporate, online, research','Enrollment: stabilize at 15K, grow to 18K','Endowment growth: $500M to $800M','Deferred maintenance: reduce from $200M to $50M'],
    ['Revenue diversification strategy','Enrollment and program innovation plan','Alumni and endowment strategy','Cost optimization and facilities plan','Financial model with 5-year revenue mix targets']),
  c('tr-20','Energy Company Coal-to-Renewables Transition','Turnaround / Restructuring','Energy / Utilities','Expert',
    'An energy company ($10B revenue) generates 70% from coal. Regulatory and market pressures are forcing a transition to renewables. They need to转型 while managing $5B in stranded assets.',
    '70% coal ($7B), 20% gas, 10% renewables. Coal declining 10% annually. Regulatory: carbon tax proposed. Stranded assets: $5B coal plants. Workers: 8,000 in coal operations.',
    ['Revenue: $10B (70% coal, 20% gas, 10% renewables)','Coal revenue: $7B (declining 10% annually)','Stranded asset risk: $5B coal plants','Carbon tax risk: $500M annually if enacted','Workers: 8,000 in coal operations','Regulatory: 2050 net-zero mandates in 12 states','Capital available: $3B over 5 years','Competitor: NextEra (largest wind/solar), Duke (coal exit)','Technology: no renewable development capability','Grid infrastructure: aging, needs $1B upgrade','Political: coal communities dependent on operations'],
    ['Renewables development strategy (wind, solar, storage)','Coal plant retirement schedule and asset write-down','Just transition plan for coal workers and communities','Gas as bridge fuel strategy','Carbon capture and storage evaluation','Regulatory and policy engagement'],
    ['Renewable capacity: 10% to 50% in 10 years','Coal phase-down: 70% to 20%','Stranded asset management: minimize write-downs','Worker transition: retrain or severance for 8,000','Revenue stability during transition: <5% annual decline'],
    ['Energy transition turnaround strategy','Renewables development and investment plan','Coal retirement and asset management','Just transition and workforce plan','Financial model with 10-year transition roadmap']),
  c('tr-21','Media Company Cord-Cutting Survival','Turnaround / Restructuring','Media / Telecommunications','Hard',
    'A cable company ($8B revenue) is losing 500K subscribers quarterly to cord-cutting. They need to transform from cable to broadband/entertainment platform.',
    'Subscribers declining from 8M to 6M. Cord-cutting: 500K/quarter. Broadband: 3M subscribers (growing). Content: no owned content. OTT: no offering.',
    ['Revenue: $8B (cable 60%, broadband 30%, other 10%)','Subscribers: 6M (declining 500K/quarter from 8M)','Broadband: 3M subscribers (growing 10% annually)','Cord-cutting rate: 500K/quarter','Content: no owned content','OTT: no offering','Competitors: Netflix, YouTube TV, Hulu','Infrastructure: DOCSIS 3.1, fiber limited','Customer satisfaction: 3.5/5','Churn: 2% monthly (benchmark 1.5%)','Employee count: 25,000'],
    ['Broadband-first strategy (upgrade infrastructure)','OTT streaming platform launch','Content acquisition and bundling','Customer retention: bundles, pricing, service','Workforce transformation from cable to digital'],
    ['Broadband: 3M to 6M subscribers in 3 years','OTT subscribers: 0 to 2M','Cable decline: manage to $2B from $5B','Total revenue: maintain $8B through diversification','Customer retention: churn from 2% to 1.2%'],
    ['Cord-cutting survival and transformation strategy','Broadband infrastructure and growth plan','OTT and content strategy','Customer retention and pricing','Financial model with revenue diversification']),
  c('tr-22','Professional Services Firm Digitization','Turnaround / Restructuring','Professional Services / Consulting','Medium',
    'A mid-tier accounting firm ($500M revenue) is losing clients to Big 4 and tech-enabled competitors. Utilization: 65% (benchmark 80%). They need to digitize or die.',
    '2,000 professionals, 200 partners. Revenue declining 8% annually. Clients: 500 (losing 10% to Big 4). Technology: basic Excel/Word. No AI, no automation.',
    ['Revenue: $500M (declining 8% annually)','Professionals: 2,000','Partners: 200','Clients: 500 (losing 10%/year to Big 4)','Utilization: 65% (benchmark 80%)','Technology: basic Excel/Word, no AI','No automation: manual audit/tax processes','Competitor: Big 4 (tech-enabled), tech startups','Pricing pressure: 20% below Big 4','Talent: losing recruits to Big 4 and tech','Brand: perceived as "old school"'],
    ['Digital transformation: AI-powered audit and tax tools','Automation of routine compliance work','Data analytics and advisory services expansion','Talent modernization and digital skills','Client experience and platform upgrade'],
    ['Revenue decline: reverse from -8% to +5%','Utilization: 65% to 80%','Client retention: stop 10% annual loss','New revenue: data analytics advisory ($50M/year)','Talent retention improvement'],
    ['Digital transformation strategy for professional services','AI and automation implementation','Advisory services expansion','Talent and client experience modernization','Financial model with revenue recovery plan']),
  c('tr-23','Aerospace Supply Chain Crisis Recovery','Turnaround / Restructuring','Aerospace / Defense','Expert',
    'An aerospace supplier ($8B revenue) has critical quality issues causing production halts at 3 major OEM customers. They face potential loss of $4B in contracts.',
    '3 OEM customers: Boeing (40% of revenue), Airbus (30%), Lockheed (20%). Quality escapes: 12 in 6 months. Production halts: 3 (costing $2B to customers). Potential contract loss: $4B.',
    ['Revenue: $8B','Customer concentration: Boeing 40%, Airbus 30%, Lockheed 20%','Quality escapes: 12 in 6 months (benchmark: 0-1)','Production halts at customers: 3','Contract loss risk: $4B','Quality cost: $500M (rework, scrap, warranty)','Workforce: 15,000','Facilities: 8 plants','ITAR compliance: critical','Regulatory: FAA/EASA scrutiny increasing','Competitor: 3 qualified alternates ready to step in'],
    ['Root cause analysis and quality system overhaul','Customer recovery and relationship rebuilding','Quality management system (AS9100) certification','Manufacturing process improvement (Six Sigma)','Supply chain quality management','Regulatory compliance and communication'],
    ['Quality escapes: 12 to 0 per year','Production halts: eliminate completely','Customer retention: keep 100% of $8B contracts','Quality cost: $500M to $100M','Regulatory compliance: zero findings'],
    ['Quality crisis recovery and turnaround strategy','Customer relationship recovery plan','Quality management system overhaul','Manufacturing and supply chain improvement','Financial model with quality cost reduction targets']),
];

const jsonPath = path.join(__dirname, '../../data/generated-cases.json');
let existing: any[] = [];
try {
  existing = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
} catch(e) {}

const seen = new Set(existing.map(c => c.id));
const newCases = moreCases.filter(c => !seen.has(c.id));
const merged = [...existing, ...newCases];
fs.writeFileSync(jsonPath, JSON.stringify(merged, null, 0), 'utf-8');
console.log(`Added ${newCases.length} new cases. Total: ${merged.length}`);
const counts: Record<string, number> = {};
merged.forEach((c: any) => { counts[c.category] = (counts[c.category] || 0) + 1; });
console.log('Cases by category:');
Object.entries(counts).sort((a,b) => b[1]-a[1]).forEach(([cat, count]) => console.log(`  ${cat}: ${count}`));