import * as fs from 'fs';
import * as path from 'path';

const allCases: any[] = [];

function c(id: string, title: string, cat: string, ind: string, diff: string, prompt: string, ctx: string, facts: string[], hints: string[], calcs: string[], crit: string[]) {
  return { id, title, category: cat, industry: ind, difficulty: diff, prompt, context: ctx, keyFacts: facts, frameworkHints: hints, expectedCalculations: calcs, successCriteria: crit };
}

// ======== GROWTH STRATEGY (20 cases) ========
const gs: any[] = [
  c('gs-01','D2C Brand Social Commerce Growth','Growth Strategy','Fashion / D2C','Medium',
    'A D2C fashion brand ($200M revenue) growing 15% YoY wants to reach 50% growth by leveraging social commerce (TikTok Shop, Instagram, live selling). Design the social commerce growth strategy.',
    'The brand sells D2C via Shopify ($200M ARR). Social media: 2M Instagram, 500K TikTok. CAC $35 via paid ads. Organic social drives 20% of traffic.',
    ['Revenue: $200M','CAC: $35 blended','Instagram: 2M followers','TikTok: 500K followers','Organic traffic: 20%','Current growth: 15% YoY','Social commerce market: $100B US by 2025','TikTok Shop GMV US: $10B growing 300%/yr','Avg order value: $65','Repeat purchase: 2.3x/year','Customer demo: 65% female, 18-35, 80% mobile-first'],
    ['Social commerce channel selection','TikTok Shop integration strategy','Live selling program design','Influencer partnership framework','Content strategy for conversion'],
    ['Revenue potential by channel','CAC reduction via social vs paid ads','Live selling ROI projection','Content investment analysis'],
    ['Social commerce strategy with channel prioritization','TikTok Shop and live selling implementation','Influencer and content strategy','3-year growth roadmap','Financial projections']),
  c('gs-02','Subscription Box Company Expansion','Growth Strategy','E-commerce / Subscription','Hard',
    'A subscription box company ($150M revenue, 500K subscribers) has plateaued at 12% growth. They want to reach 30% growth through new verticals (pet, kids, wellness) and geographic expansion (UK, Germany).',
    'Monthly beauty boxes ($40/mo avg). 18-month lifetime. NRR 85%. Churn 8%/mo. Profitable with $20M EBITDA.',
    ['Revenue: $150M','Subscribers: 500K','Avg box: $40/mo','Churn: 8%/mo','Lifetime: 18 months','NRR: 85%','EBITDA: $20M','CAC: $45','LTV: $540','Growth: 12% (was 25% 3 yrs ago)'],
    ['New vertical opportunity assessment','Geographic expansion analysis','Product-market fit validation','Supply chain for new verticals','Customer acquisition strategy'],
    ['New vertical TAM and revenue projection','Geographic expansion unit economics','CAC and LTV by vertical/geography','Revenue at 30% growth','Investment required'],
    ['Growth strategy with channel prioritization','New vertical launch plan','Geographic expansion roadmap','Financial projections','Risk assessment']),
  c('gs-03','Healthcare Platform B2B2C Growth','Growth Strategy','Healthcare / Tech','Hard',
    'A telemedicine platform ($300M revenue) wants to grow from 5M to 15M users in 3 years through employer partnerships, insurance bundling, and direct consumer marketing.',
    'B2C subscriptions ($49/mo for unlimited primary care). 5M active users. Employer adoption at 200 companies. Gross margin 55%. Burn rate $5M/mo.',
    ['Revenue: $300M','Active users: 5M','Subscription: $49/mo','Employers: 200','Gross margin: 55%','CAC: $25 B2C, $5/employee B2B2C','NRR: 110%','Churn: 5%/mo','Burn: $5M/mo','Runway: 18 months'],
    ['Employer partnership strategy','Insurance bundling partnerships','Direct consumer marketing','Channel partner enablement','Product-market fit validation'],
    ['Employer channel revenue potential','Insurance bundling unit economics','CAC comparison across channels','Revenue at 15M users','Path to profitability'],
    ['B2B2C growth strategy with channel prioritization','Employer and insurance partnership roadmap','Consumer marketing plan','Financial model and path to profitability','Risk mitigation']),
  c('gs-04','SaaS Land-and-Expand Strategy','Growth Strategy','Software / SaaS','Easy',
    'A B2B SaaS company ($80M ARR) lands SMBs ($5K ACV) and wants to grow by expanding into enterprise ($50K+ ACV) and launching a self-serve SMB product.',
    'Currently 1,500 SMB customers, 30 AEs. Win rate 25%, sales cycle 45 days. Enterprise untapped. No self-serve product.',
    ['Revenue: $80M','Customers: 1,500 SMBs','ACV: $5K','Win rate: 25%','AEs: 30','NRR: 105%','Gross margin: 75%','No enterprise product','No self-serve product','Market: enterprise $50B, SMB $20B'],
    ['Enterprise product roadmap','Self-serve product design','Land-and-expand customer journey','Sales team restructure','Pricing and packaging'],
    ['Enterprise revenue potential','Self-serve product TAM','CAC by segment','Revenue at target mix','Investment needed'],
    ['Land-and-expand growth strategy','Enterprise and self-serve product plans','Sales and GTM strategy','Financial projections','Risk assessment']),
  c('gs-05','QSR Digital Growth','Growth Strategy','Restaurant / F&B','Medium',
    'A QSR chain ($3B revenue, 1,500 locations) wants to grow 25% YoY through digital ordering, loyalty program, and delivery partnerships. Currently 8% digital mix vs 35% industry.',
    'Average check $12. 30% drive-through. Online/app 8%. Delivery via DoorDash (25% commission). 800K loyalty members with low engagement.',
    ['Revenue: $3B','Locations: 1,500','Digital orders: 8% (industry 35%)','Avg check: $12','Loyalty: 800K','Delivery commission: 25%','App rating: 3.2/5','NPS: 45','Visit freq: 1.8x/month','Drive-through: 30%'],
    ['Digital ordering investment and ROI','Loyalty program redesign','Delivery channel strategy','Store technology deployment','Consumer app redesign'],
    ['Digital revenue uplift 8% to 25%','Loyalty program ROI','App development cost','Drive-through digital benefit','Delivery channel economics'],
    ['Digital growth strategy','Loyalty program redesign','Technology and app roadmap','Delivery channel optimization','Financial projections']),
  c('gs-06','Insurance Cross-Sell Acceleration','Growth Strategy','Insurance / Financial','Hard',
    'A P&C insurer ($5B premiums) cross-sells at 15% rate (vs industry 25%). They want to reach 30% cross-sell rate in 2 years by leveraging data analytics and bundling.',
    'Cross-sell: 15% have 2+ policies. Benchmark 25%. Auto 3M, Home 2M, Umbrella 500K. LTV doubles with 2+ policies.',
    ['Premiums: $5B','Customers: 5M','Cross-sell: 15% (benchmark 25%)','LTV per policy: $800/yr','LTV with 2+: $1,400/yr','Auto 3M, Home 2M, Umbrella 500K','Bundle discount: 10%','Retention: 90% single, 95% bundled','NPS: 35','Distribution: 60% agents, 40% direct'],
    ['Cross-sell opportunity by segment','Data analytics propensity modeling','Bundling strategy and discount design','Agent incentive redesign','Digital experience for bundling'],
    ['Cross-sell revenue uplift 15% to 30%','Bundle discount margin impact','LTV improvement from bundling','Data analytics investment and ROI','Conversion rate targets by channel'],
    ['Cross-sell growth strategy','Data analytics and propensity scoring','Bundle pricing and incentive design','Agent enablement and training','Financial projections and timeline']),
  c('gs-07','Consumer Marketplace Vertical Expansion','Growth Strategy','Consumer / Marketplace','Medium',
    'A consumer marketplace ($1B GMV) wants to expand from 3 verticals (furniture, electronics, fashion) to 8 verticals (adding food, health, beauty, pet, home).',
    'Marketplace connects 20K sellers with 5M customers. GMV growing 20% YoY. Take rate 15%. CAC $15.',
    ['GMV: $1B','Take rate: 15%','Customers: 5M','Sellers: 20K','Growth: 20% YoY','CAC: $15','Seller onboarding: 2 weeks','Retention: 70% annual','Current verticals: 3','Target: 8 verticals'],
    ['New vertical selection framework','Seller acquisition for new verticals','Marketplace liquidity building','Category-specific marketing','Logistics strategy'],
    ['New vertical revenue potential','Seller acquisition cost','Customer acquisition cost for new verticals','TAM for 8 verticals','Revenue growth to 2030'],
    ['Vertical expansion strategy','Go-to-market for each vertical','Seller and customer acquisition','Financial projections','Risk assessment and phasing']),
  c('gs-08','EdTech Geographic Expansion','Growth Strategy','Education / EdTech','Hard',
    'An Indian edtech platform ($50M revenue, 10M users) wants to expand to 3 African countries (Nigeria, Kenya, Ethiopia) and 2 Southeast Asian markets.',
    'Online test prep and skill development. India ARPU $5/month. African ARPU expected $1/month but TAM 5x India. Mobile-first.',
    ['Revenue: $50M','Users: 10M','ARPU: $5/mo India','Growth: 40% YoY','Retention: 75%','Target: Nigeria, Kenya, Ethiopia, Vietnam, Philippines','Mobile-first: 90%','Internet: 50-70% penetration','Payment: mobile money dominant'],
    ['Market prioritization framework','Product localization','Payment infrastructure','Content and language adaptation','Partnership strategy'],
    ['Revenue projection by market','Market sizing (TAM/SAM/SOM) by country','CAC and LTV by market','Content localization cost','Go-to-market budget per market'],
    ['Global expansion strategy with market prioritization','Product and content adaptation','Payment and distribution infrastructure','Country-by-country launch roadmap','Financial model and funding']),
  c('gs-09','B2B Software Channel Partner Growth','Growth Strategy','Software / B2B SaaS','Easy',
    'A B2B analytics software company ($200M revenue) sells directly to enterprises. They want to grow 40% YoY by building a channel partner program (resellers, MSPs, consultants).',
    'Currently 100% direct sales. 200 enterprise customers, $1M ACV. Win rate 30%. Sales team: 40 AEs.',
    ['Revenue: $200M','Customers: 200 enterprises','ACV: $1M','Win rate: 30%','AEs: 40','No channel partners','NRR: 120%','Gross margin: 70%','Market: $30B','Target: 40% growth = $80M incremental'],
    ['Channel partner program design','Partner tier structure and economics','Enablement and certification','Co-selling and joint GTM','Competitive partner economics'],
    ['Channel revenue potential','Partner economics (margin, revenue share)','CAC via partners vs direct','Revenue per partner over 3 years','Partner program ROI'],
    ['Channel partner growth strategy','Partner program economics and tiers','Enablement and certification plan','Co-selling and joint GTM strategy','Financial projections']),
  c('gs-10','Travel Platform Super App','Growth Strategy','Travel / Technology','Medium',
    'A travel platform ($1.5B revenue) wants to transform from flights-only into a super app (flights + hotels + experiences + car rental + insurance) to grow from 20M to 50M users.',
    'Flight booking only. 20M users, $1.5B revenue. Take rate 5% on flights. Hotels and experiences could add 2x revenue.',
    ['Revenue: $1.5B','Users: 20M','Take rate: 5% flights','Growth: 15% YoY','Booking freq: 2x/year','Cross-sell: 20% book hotel after flight','Hotel AOV: $150/night','Car rental: $50/day','Experience AOV: $80','CAC: $8','Retention: 60% annual'],
    ['Hotel and experience marketplace design','Car rental and insurance partnerships','Cross-sell conversion optimization','Platform technology architecture','Brand evolution'],
    ['Revenue by new vertical','Cross-sell conversion modeling','Customer acquisition cost by vertical','TAM for super app','Revenue at 50M users'],
    ['Super app growth strategy','Vertical expansion roadmap','Technology and platform plan','Partnership and supplier strategy','Financial model and projections']),
  c('gs-11','Fitness Franchise Licensing','Growth Strategy','Fitness / Franchise','Easy',
    'A fitness brand ($100M revenue, 50 corporate gyms) wants to grow 30% YoY through franchising. Target: 200 franchise locations in 3 years.',
    'Corporate gyms: $1.2M avg revenue, 18% EBITDA. Franchise model: $50K fee, 6% royalty. Franchisee profile: investor/operator.',
    ['Revenue: $100M','Corporate gyms: 50','Revenue/gym: $1.2M','EBITDA margin: 18%','Franchise fee: $50K','Royalty: 6%','Franchisee ROI target: 25%','Gym investment: $500K-$1M','Territory: 50K pop','Target: 200 locations 3 years'],
    ['Franchise model economics','Franchisee recruitment and onboarding','Territory and market sizing','Brand standards and operations manual','Technology platform for franchise management'],
    ['Franchise unit economics (franchisee and franchisor)','Revenue from royalties vs corporate','Investment per location','Payback period for franchisees','Total revenue at 200 locations'],
    ['Franchise growth strategy with economics','Franchisee recruitment plan','Territory analysis and selection','Operations and brand standards','Financial model and growth timeline']),
  c('gs-12','Logistics Company Marketplace','Growth Strategy','Logistics / Marketplace','Hard',
    'A logistics company ($2B revenue) operates 500 trucks. They want to grow 30% YoY by launching a trucking marketplace connecting independent owner-operators with shippers.',
    'Asset-based logistics with 500 trucks. Revenue $2B, 8% margin. Marketplace could serve 100K truckers and 50K shippers. Take rate 10-15%.',
    ['Revenue: $2B','Trucks: 500','Margin: 8%','Independent truckers: 100K potential','Shippers: 50K potential','Take rate: 10-15%','Marketplace GMV potential: $2B','Technology: $20M build, $5M/yr operate','Customer acquisition: $200/shipper'],
    ['Marketplace design and value proposition','Truck operator recruitment','Shipper acquisition','Technology platform build vs buy','Trust and safety framework'],
    ['Marketplace GMV projection','Take rate revenue model','Platform cost and ROI','Customer acquisition cost by side','Network effects and unit economics'],
    ['Marketplace growth strategy','Supply and demand acquisition','Technology platform plan','Trust and safety framework','Financial model and projections']),
  c('gs-13','Ghost Kitchen Expansion','Growth Strategy','Restaurant / F&B','Medium',
    'A restaurant brand ($500M revenue, 300 stores) wants to grow 40% YoY by opening 500 ghost kitchen locations in 3 years.',
    'Physical stores: 300, avg $1.6M revenue, 15% margin. Ghost kitchens: $100K setup, $600K revenue, 20% margin.',
    ['Revenue: $500M','Physical: 300 stores','Revenue/store: $1.6M','Physical margin: 15%','Ghost kitchen setup: $100K','Ghost kitchen revenue: $600K','Ghost kitchen margin: 20%','Delivery: 40% of orders','Target: 500 ghost kitchens 3 years'],
    ['Ghost kitchen site selection','Virtual brand design','Kitchen operations and logistics','Marketing for delivery-first brands','Technology for order management'],
    ['Ghost kitchen unit economics','Revenue per ghost kitchen by brand','Investment per location','Payback period and ROI','Revenue at 500 ghost kitchens'],
    ['Ghost kitchen expansion strategy','Site selection and launch plan','Virtual brand portfolio strategy','Operations and quality framework','Financial model and growth timeline']),
  c('gs-14','Nonprofit Program Scaling','Growth Strategy','Nonprofit / Social Impact','Easy',
    'A nonprofit education platform ($30M revenue) helps 500K students in 5 African countries. They want to grow to 5M students in 5 countries.',
    'Free basic tier, premium $2/mo. Current ARPU $3. Completion rate 40%. Mobile-first.',
    ['Revenue: $30M','Students: 500K','ARPU: $3/mo blended','Countries: 5','Premium tier: $2/mo','Completion rate: 40%','Internet penetration: 60%','Smartphone: 55%','Funding: 60% donor-funded','Retention: 50%'],
    ['Program expansion strategy','Donor funding diversification','Mobile delivery optimization','Partnership model with schools and telcos','Impact measurement framework'],
    ['Student growth projection','Revenue model (premium + donor funding)','Mobile delivery cost per student','Partnership revenue sharing','Impact metrics and funding'],
    ['Scaling strategy with country prioritization','Mobile delivery optimization','Partnership and funding model','Impact measurement framework','5-year growth roadmap']),
  c('gs-15','E-commerce Marketplace International','Growth Strategy','E-commerce / Marketplace','Hard',
    'A US-based home goods marketplace ($1B GMV) wants to expand to 5 European countries. Currently US-only with 20K sellers and 2M customers.',
    'GMV growing 20% YoY. Take rate 12%. CAC $20. 80% retention. US-centric logistics.',
    ['GMV: $1B','Take rate: 12%','Customers: 2M','Sellers: 20K','Growth: 20% YoY','CAC: $20','Retention: 80% annual','Logistics: US-centric','Target: 5 EU countries (UK, DE, FR, NL, Nordics)','Intl launch: $50M/market'],
    ['International market prioritization','Localization strategy','Logistics infrastructure','Seller and customer acquisition','Legal and regulatory compliance'],
    ['Market sizing by country','CAC and LTV by European market','Logistics cost and delivery SLA','Revenue projection for each market','Total investment and ROI'],
    ['International expansion strategy','Localization and go-to-market','Seller and customer acquisition','Logistics infrastructure','Financial model and 3-year roadmap']),
  c('gs-16','MedTech Partner Growth','Growth Strategy','Healthcare / MedTech','Hard',
    'A medical device company ($3B revenue) wants to grow 20% YoY by partnering with hospital networks, insurance companies, and government health programs.',
    'Diagnostic imaging equipment ($50K-$500K per unit). 5,000 installed base. Service revenue: $500M/yr.',
    ['Revenue: $3B','Products: diagnostic imaging ($50K-$500K/unit)','Installed base: 5,000','Service revenue: $500M/yr','Margin: 40% equipment, 60% service','Partner potential: hospital networks, insurers, gov programs','US market: 6,000 hospitals','Digital health market: $50B growing 25%/yr'],
    ['Partner ecosystem design','Hospital network bundling','Insurance and government partnerships','AI/digital health product development','Channel partner economics'],
    ['Revenue from partner channel','Hospital network partnership revenue','Bundling economics (equipment + AI + service)','Market sizing by partner type','Growth rate with partner strategy vs direct'],
    ['Partner-driven growth strategy','Hospital network and insurer partnerships','AI/digital health product roadmap','Financial projections for partner channel','Implementation timeline']),
  c('gs-17','Influencer-Driven Growth','Growth Strategy','Consumer / Brand','Easy',
    'A consumer beverage brand ($500M revenue) wants to grow 25% YoY through influencer marketing, creator partnerships, and UGC campaigns.',
    'Traditional advertising (TV, print, digital). Sales: $500M, 10% growth. Influencer budget: $20M. ROI 5x vs traditional. 1M Instagram.',
    ['Revenue: $500M','Growth: 10% (target 25%)','Influencer budget: $20M','Influencer ROI: 5x','Instagram: 1M followers','TikTok: 200K','Traditional ad spend: $100M','Brand awareness: 60% target demo','CAC: $12','LTV: $180'],
    ['Influencer program tier design','Creator partnership models','UGC content strategy','Paid social optimization','Brand storytelling'],
    ['Influencer marketing ROI by tier','CAC via influencer vs paid vs organic','Content creation cost per asset','Community growth metrics','Revenue attribution to influencer programs'],
    ['Influencer-led growth strategy with tier structure','Content and community strategy','Paid social and influencer optimization','Financial model and ROI projections','Implementation timeline']),
  c('gs-18','SaaS Multi-Segment Growth','Growth Strategy','Software / B2B SaaS','Easy',
    'A B2B analytics tool ($30M ARR, 500 SMB customers) wants to grow 40% YoY by adding enterprise features, expanding to mid-market, and launching freemium.',
    '500 SMB customers, $60K ACV, 95% retention. Enterprise untapped. No freemium. Sales team: 15 AEs.',
    ['ARR: $30M','Customers: 500','ACV: $60K','Retention: 95%','NRR: 110%','AEs: 15','Win rate: 35%','Sales cycle: 90 days','No freemium','No enterprise product','Market: SMB $10B, mid $15B, enterprise $25B'],
    ['Enterprise product requirements','Mid-market GTM strategy','Freemium tier design and conversion plan','Sales team restructure','Product roadmap prioritization'],
    ['Enterprise revenue potential','Freemium-to-paid conversion modeling','CAC by segment','Revenue at target mix','Total market opportunity'],
    ['Multi-segment growth strategy','Product roadmap for enterprise and freemium','Sales and GTM strategy','Financial projections 3 years','Resource allocation and hiring plan']),
  c('gs-19','Healthcare Provider Network Growth','Growth Strategy','Healthcare / Provider','Medium',
    'A healthcare staffing company ($1B revenue) wants to grow 20% YoY by expanding into telehealth staffing, home health care, and locum tenens markets.',
    'Temporary nurse staffing only. 50K nurses placed annually. Revenue $1B, 8% margin. Healthcare staffing market is $40B.',
    ['Revenue: $1B','Nurses placed: 50K/year','Margin: 8%','Healthcare staffing: $40B','Current: nurse staffing only','Adjacent: telehealth, home health, locums','Telehealth: $15B growing 25%/yr','Home health: $10B growing 12%/yr','Locum tenens: $5B growing 15%/yr'],
    ['New vertical opportunity assessment','Recruiter hiring and training','Client acquisition by vertical','Technology platform for operations','Pricing and margin by vertical'],
    ['Revenue by new vertical','Recruiter productivity and cost','CAC by vertical and client type','Market sizing by new vertical','Revenue at 20% growth'],
    ['Expansion strategy with vertical prioritization','Recruiter and staffing plan','Client acquisition and retention','Financial model and investment needs','Risk assessment and timeline']),
  c('gs-20','Media Company Audience Growth','Growth Strategy','Media / Entertainment','Hard',
    'A media company ($2B revenue) owns TV channels, digital media, and streaming. Audience declining on TV but growing on digital. They want 15% YoY growth through digital-first audience expansion.',
    'TV: $1B (declining 5%). Digital: $500M (growing 30%). Streaming: $500M (growing 25%). Total audience: 50M monthly. Digital: 20M. Social: 5M.',
    ['Revenue: $2B','TV: $1B declining 5%','Digital: $500M growing 30%','Streaming: $500M growing 25%','Audience: 50M monthly','Digital audience: 20M','Social: 5M','Content library: 100K hours','Ad CPM: $15','Streaming ARPU: $8/mo'],
    ['Digital audience growth channels','Content strategy for digital-first','Streaming subscriber acquisition','Social media audience building','Cross-platform audience monetization'],
    ['Digital audience revenue per user','Streaming subscriber growth and churn','Ad revenue by digital channel','Content investment for digital formats','Total revenue at 50M digital users'],
    ['Digital-first audience growth strategy','Content and programming strategy','Streaming and digital platform plan','Social media and community building','Financial model and audience projections']),
];

// ======== OPERATIONS / SUPPLY CHAIN (20 cases) ========
const ops: any[] = [
  c('ops-01','E-commerce Fulfillment Network Redesign','Operations / Supply Chain','E-commerce / Logistics','Medium',
    'An e-commerce company doing $2B in annual sales is spending 22% of revenue on fulfillment (vs 15% benchmark). They have 3 warehouses. Redesign their fulfillment network.',
    'The company sells bulky items (furniture, home goods). Free 2-day shipping over $50. 70% of orders $50-200. Peak season 40% of sales.',
    ['Revenue: $2B','Fulfillment cost: $220M (22% of revenue)','Industry benchmark: 15%','Current warehouses: 3 (NJ, IL, NV)','50,000 SKUs','Avg order value: $120','16.7M orders/year','Avg package weight: 25 lbs','Service level: 92% on-time','Inventory turns: 4x (industry 6x)','Return rate: 15%','Peak surge: 3x normal volume','Last-mile cost: 40% of fulfillment','Carrier mix: 60% FedEx/UPS, 40% USPS'],
    ['Network optimization (warehouse count and location)','Zone skipping and transportation optimization','Inventory management improvement','Automation and technology investment','Last-mile alternatives'],
    ['Transportation cost by zone analysis','Warehouse optimization ROI','Inventory reduction potential','Network redesign financial impact','Peak season capacity cost-benefit'],
    ['Network design recommendation','Cost savings quantification ($40M+ target)','Service level improvement plan','Implementation timeline','Technology and automation strategy']),
  c('ops-02','Hotel Revenue Management Overhaul','Operations / Supply Chain','Hospitality','Hard',
    'A hotel chain with 500 properties has seen RevPAR decline 8% YoY despite stable occupancy. Their revenue management system is outdated.',
    'Luxury, business, and resort hotels. Competition from OTAs and Airbnb. Rule-based pricing updated quarterly.',
    ['Properties: 500 across 20 countries','Rooms: 125,000','Revenue: $5B annually','Occupancy: 70% (flat)','ADR: $190 (down 5%)','RevPAR: $133 (down 8%)','OTA commission: 18% of online revenue','Direct channel share: 35% (benchmark 40%)','Group business: 25% (down from 35%)','RMS: 15 years old, rule-based','Competition: Marriott, Hilton, Accor investing in AI RMS','Seasonal variation: resorts 80% peak / 40% off-peak'],
    ['RMS modernization (AI/ML-based)','Distribution channel optimization','Pricing strategy by segment and season','Direct booking and loyalty enhancement','Group and corporate business strategy'],
    ['Revenue uplift from RMS optimization (3-5%)','OTA commission savings from direct channel shift','Dynamic pricing revenue impact','Technology investment and ROI','RevPAR recovery trajectory'],
    ['RMS transformation strategy','Technology platform recommendation','Channel mix optimization','Revenue uplift projection ($150M+)','Capability building plan']),
  c('ops-03','Manufacturing Plant Productivity','Operations / Supply Chain','Manufacturing','Easy',
    'A manufacturing plant is operating at 70% OEE (overall equipment effectiveness) vs 85% world-class benchmark. Identify improvement opportunities.',
    '500 workers, 3 shifts, 10K units/day. 50 CNC machines, 5 assembly lines. JIT contracts with 3 OEMs.',
    ['Current OEE: 70% (Availability 80%, Performance 90%, Quality 97%)','World-class target: 85%','Planned downtime: 12%','Unplanned downtime: 8%','Changeover: 4 hours per batch (6x/month)','Defect rate: 3% (benchmark 2%)','Inventory turns: 8x (benchmark 12x)','Lead time: 3 weeks','Labor efficiency: 85% (benchmark 90%)','Energy cost: 15% of manufacturing cost'],
    ['Identify largest OEE loss areas','TPM implementation','SMED for changeover reduction','Lean manufacturing and waste elimination','Workforce engagement and continuous improvement'],
    ['Production capacity increase from OEE improvement','Cost savings from reduced downtime','Changeover time reduction impact','Revenue impact of increased capacity'],
    ['OEE improvement target and plan','Focus areas with highest impact','Lean implementation roadmap','Investment requirements and ROI','Expected productivity increase']),
  c('ops-04','Cold Chain Logistics Quality','Operations / Supply Chain','Pharma / Logistics','Expert',
    'A pharma logistics provider ($2B revenue) has 98.5% cold chain compliance but 1.5% failures cost $400M in product losses. Clients demand 99.9%+.',
    'Temperature-sensitive biologics, vaccines, gene therapies. 50 cold storage warehouses, 2,000 refrigerated trucks. Product value per pallet up to $5M.',
    ['Revenue: $2B, cold chain 70%','Compliance: 98.5% (target 99.9%+)','Failure cost: $400M/yr in product losses','SLA: 99.9% temp compliance for new contracts','Warehouses: 50, trucks: 2,000 temp-controlled','Sensors: basic monitoring, no real-time visibility','Avg product value: $500K per pallet (up to $5M gene therapy)','Key clients: Pfizer, Moderna, J&J, Novartis','Margin: 15% on cold chain services'],
    ['Temperature excursion root cause analysis','Real-time IoT monitoring deployment','Packaging innovation (passive vs active)','Warehouse automation and validation','SOP redesign and training'],
    ['Failure cost reduction from $400M to $40M (99.9% compliance)','IoT monitoring investment and ROI','Packaging cost vs failure risk trade-off','Training and SOP improvement impact','Total cost of quality investment and return'],
    ['Zero-defect cold chain strategy','Technology and monitoring investment plan','Process improvement and SOP redesign','Client SLA compliance roadmap','Risk and insurance optimization']),
  c('ops-05','Last-Mile Delivery Optimization','Operations / Supply Chain','Logistics','Hard',
    'A last-mile delivery company ($800M revenue) delivers 200M packages annually. Cost per delivery is $4.00 (20% above competitors). Driver turnover is 120%.',
    '5,000 delivery vans, 200 hubs. Competition from Amazon Logistics, UPS, FedEx. Density is the key driver of unit economics.',
    ['Revenue: $800M, packages: 200M','Cost per delivery: $4.00 (competitors $3.20-3.50)','Driver turnover: 120% (costs $50M to replace)','Fleet: 5,000 vans (avg age 5 years, 15mpg)','Hubs: 200, utilization 60%','Delivery density: 8 packages/route-mile (target 12)','Failed delivery rate: 5% (target 2%)','Customer satisfaction: 75% (target 90%)'],
    ['Route optimization and density improvement','Driver retention and compensation redesign','Fleet electrification and maintenance','Hub network redesign','Technology for real-time tracking'],
    ['Cost per delivery reduction levers ($4.00 to $3.40)','Driver retention improvement financial impact','Route density improvement strategy','Fleet and hub optimization savings','Total savings target: $120M annually'],
    ['Root cause diagnosis of cost gap','Route and density optimization plan','Driver retention program redesign','Technology investment roadmap','Implementation timeline with $120M savings']),
  c('ops-06','Pharma Supply Chain Digital Twin','Operations / Supply Chain','Pharma / Technology','Medium',
    'A pharmaceutical company ($10B revenue) has 15 distribution centers and complex global supply chains. They want to reduce waste, improve forecasting, and digitize operations using IoT and AI.',
    '15 DCs worldwide. 10,000+ SKUs. 5,000 pharma customers. Manual inventory management. 8% waste rate. Demand forecasting accuracy: 70%.',
    ['Revenue: $10B','DCs: 15 worldwide','SKUs: 10,000+','Customers: 5,000 pharma','Waste rate: 8% (target 3%)','Forecast accuracy: 70% (target 90%)','Inventory carrying cost: $500M','Delivery failures: 5% (lost sales + reship cost)','IT systems: fragmented (10+ legacy systems)','Competition: McKesson, Cardinal Health investing in digital'],
    ['IoT sensor deployment across supply chain','AI/ML demand forecasting platform','Warehouse automation and robotics','Real-time visibility dashboard','Supplier collaboration portal'],
    ['Waste reduction from 8% to 3% ($500M savings)','Forecast accuracy improvement revenue impact','Inventory carrying cost reduction potential','Delivery failure reduction savings','Total ROI from digital transformation'],
    ['Digital supply chain transformation strategy','Technology architecture and platform design','Phased implementation roadmap','Change management and training program','Financial business case with quantified ROI']),
];

// ======== M&A / CORPORATE STRATEGY (20 cases) ========
const ma: any[] = [
  c('ma-01','Food Conglomerate Acquisition Strategy','M&A / Corporate Strategy','Consumer Packaged Goods','Hard',
    'A global food conglomerate ($15B revenue) wants to acquire growth in the plant-based protein market. They have $2B to deploy.',
    'Strong in dairy, meat, and snacks. Plant-based is growing 15% annually. They have acquired 3 small brands with mixed success.',
    ['Revenue: $15B (dairy 40%, meat 35%, snacks 25%)','Growth: 2% annually (flat volumes)','Plant-based market: $8B in US, growing 15% annually','Leaders: Beyond Meat ($400M rev), Impossible ($500M)','Valuations: Beyond Meat 3x rev, private cos 4-6x','Acquisition budget: $2B (debt + cash)','Historical M&A: 3 small brands ($50-100M each), 2 underperforming','Synergy: distribution (50K retail doors), manufacturing, R&D','Consumer overlap: 40% buy plant-based','Cultural integration challenge: high with entrepreneurial brands'],
    ['Platform acquisition vs tuck-in approach','Synergy quantification and integration strategy','Valuation and return analysis','Portfolio strategy (sub-segments to target)','Risk assessment (market evolution, competition)'],
    ['Market sizing by sub-segment','ROI for different acquisition targets','Synergy realization timeline and value','Dilution/accretion analysis','Integration cost assessment'],
    ['Clear acquisition target recommendation','Valuation and deal structure proposal','Integration plan and timeline','Synergy quantification','Risk mitigation strategy']),
  c('ma-02','Media Company Divestiture Decision','M&A / Corporate Strategy','Media / Entertainment','Medium',
    'A traditional media company ($5B revenue) considers divesting their newspaper division. Newspapers contribute 20% of revenue but 0% profit growth.',
    'TV and digital growing 8% annually. Print declining 10%. Multiple offers received. Employee implications significant.',
    ['Total revenue: $5B (TV 50%, Digital 30%, Print 20%)','EBITDA: $1.5B (30% margin)','Print: $1B revenue, $50M EBITDA (5% margin, declining 10%)','TV: $2.5B revenue, $875M EBITDA (35% margin, growing 5%)','Digital: $1.5B revenue, $575M EBITDA (38% margin, growing 10%)','Print decline: revenue -10%, EBITDA -20%','Offer received: $800M (8x EBITDA)','Divestiture cost: $50M','Tax implications: 21% capital gains on $500M gain','Employee impact: 1,500 print employees, severance $30M'],
    ['Financial analysis (valuation, use of proceeds)','Strategic fit and portfolio optimization','Synergies lost vs costs freed up','Timing and cycle analysis','Alternative strategies (turnaround, spin-off, partial sale)'],
    ['Net proceeds after tax and costs','EPS impact (accretion/dilution)','ROI: debt reduction vs reinvestment','Value creation from alternative use of proceeds','Multi-year projection with and without divestiture'],
    ['Recommendation with financial rationale','Use of proceeds strategy','Future portfolio vision','Stakeholder management plan','Timing and execution roadmap']),
  c('ma-03','PE Roll-Up Strategy','M&A / Corporate Strategy','Software / SaaS','Expert',
    'A PE firm wants to create a $1B+ SaaS platform by rolling up 15-20 niche vertical SaaS companies in logistics technology. $500M equity + 3x debt.',
    'Logistics tech market highly fragmented. Hundreds of small SaaS companies. Most have $5-50M ARR. Competition from Thoma Bravo, Vista Equity.',
    ['Target market: Logistics tech SaaS, fragmented, $50B total','Target: 15-20 niche players ($5-50M ARR each)','Equity: $500M','Leverage: 3x debt at 6%','Target returns: 3x MOIC in 5 years, 25% IRR','Target valuation: 4-6x ARR (platforms trade 8-12x)','Synergy: Cross-sell (30% uplift), cost savings (20% G&A), tech consolidation','Integration cost: 15-20% of acquired ARR','Current portfolio: 3 companies ($80M combined ARR)','Management: experienced, 5 bolt-ons completed','Competition: Thoma Bravo, Vista Equity','Market growth: 12% CAGR logistics tech'],
    ['Target screening and prioritization framework','Roll-up sequencing (platform first vs tuck-ins)','Integration strategy (centralized vs federated)','Value creation levers (cross-sell, cost save, tech)','Exit strategy options (IPO, strategic sale, dividend recap)'],
    ['Pro forma financial model with all acquisitions','Synergy quantification (revenue and cost)','IRR and MOIC under different scenarios','Deployment timeline and capital structure','Exit valuation analysis'],
    ['Target identification and prioritization framework','Roll-up playbook with integration blueprint','Pro forma financials and return analysis','Risk mitigation strategy','Org design and management team plan']),
  c('ma-04','Cross-Border Grocery Merger','M&A / Corporate Strategy','Retail / Consumer Goods','Hard',
    'A UK-based grocery chain ($20B revenue) considers a merger of equals with a US grocery chain of similar size. Combined would be 3rd largest globally.',
    'UK chain: strong private label, efficient supply chain, urban stores. US chain: fresh/organic strength, loyalty programs, suburban stores. Both face margin pressure from discounters.',
    ['UK chain: $20B revenue, EBITDA margin 6%','US chain: $22B revenue, EBITDA margin 5.5%','Combined market cap: $15B','Store count: UK 2,500, US 1,800 (no overlap)','Private label: UK 50%, US 25%','Fresh/organic: UK 20%, US 45%','E-commerce: UK 8%, US 12%','Cost synergies: $500M-800M/yr (procurement, tech, G&A)','Revenue synergies: cross-format learning','Integration cost: $1-1.5B over 3 years','Regulatory risk: FTC and CMA scrutiny','Shareholders: UK 30% family-owned, US 40% institutional'],
    ['Strategic rationale assessment','Integration approach (speed vs thoroughness)','Cultural integration and leadership selection','Regulatory strategy (antitrust, foreign investment)','Value capture tracking and governance'],
    ['Synergy quantification and phasing','Integration cost and NPV of synergy','Accretion/dilution analysis','Combined entity pro forma financials','Regulatory risk probability and cost scenarios'],
    ['Merger rationale with value creation','Integration blueprint with Day 1 readiness','Org design and leadership recommendations','Regulatory and stakeholder strategy','Risk mitigation for execution challenges']),
  c('ma-05','Tech Company Strategic Acquisition','M&A / Corporate Strategy','Technology','Expert',
    'A mid-sized tech company ($5B revenue) has $1B cash and $2B in borrowing capacity. They want to acquire an AI startup ($1-3B valuation) to add ML capabilities across their product suite.',
    'Current product: enterprise software. AI capabilities are table-stakes in the market. 3 AI startups in target range. Internal R&D has failed for 2 years.',
    ['Company revenue: $5B','Cash: $1B','Debt capacity: $2B','Target: AI startup $1-3B valuation','Current AI capabilities: basic (no proprietary models)','Market AI adoption: 85% of enterprises using AI features','Internal R&D: failed for 2 years ($100M spent)','Competitors: Microsoft (OpenAI), Google, AWS','Key target attributes: proprietary models, team, customers','Retention risk: key engineers may leave post-acquisition','Integration challenge: different culture (startup vs enterprise)'],
    ['Target evaluation framework (tech, team, customers, IP)','Valuation sensitivity analysis ($1B vs $3B)','Integration strategy (keep separate vs full integration)','Retention plan for key talent','Synergy quantification across product portfolio'],
    ['Target valuation multiples and comparables','Synergy realization potential','Integration cost timeline','Revenue uplift from AI capabilities','ROI under different deal structures'],
    ['Recommendation on target and valuation','Integration strategy and timeline','Talent retention plan','Synergy quantification and tracking','Risk assessment (overpaying, integration failure)']),
  c('ma-06','Healthcare System Merger Evaluation','M&A / Corporate Strategy','Healthcare','Hard',
    'A regional health system ($3B revenue) is evaluating merging with a competing system ($1.5B) to create a dominant player in the Southeast US. Combined would serve 5M patients.',
    'Current system is profitable (8% margin). Competitor has better clinical outcomes but weaker finances. Both systems face rural hospital closures and rising costs.',
    ['System 1: $3B revenue, 8% margin, 20 hospitals','System 2: $1.5B revenue, 3% margin, 10 hospitals','Combined: $4.5B, 30 hospitals, 5M patients','Market: Southeast US, 3 major competitors','Cost synergies: $150M (shared back-office, procurement)','Revenue synergies: limited (no geographic overlap)','Integration risk: 2 different EMR systems ($50M migration)','Antitrust: may require divestiture of 2-3 overlapping hospitals','Physician retention: critical for clinical quality','Regulatory: state-by-state approval needed'],
    ['Strategic rationale and competitive analysis','Synergy quantification (cost and revenue)','Integration complexity assessment (IT, clinical, cultural)','Regulatory approval strategy (antitrust, state)','Physician and employee retention plan'],
    ['Merger cost-benefit analysis','Synergy phasing over 3 years','Integration risk-adjusted NPV','Physician retention cost estimate','Regulatory timeline and approval probability'],
    ['Merger recommendation with risk assessment','Synergy quantification and tracking','Integration execution plan','Physician and stakeholder retention','Regulatory strategy and timeline']),
];

// ======== M&A/Corporate STRATEGY (remaining cases) ========
const maMore: any[] = [
  c('ma-07','Media Conglomerate Portfolio Review','M&A / Corporate Strategy','Media / Entertainment','Medium',
    'A $10B media conglomerate wants to evaluate its portfolio of 6 business units. 3 are growing but low margin, 3 are mature but high margin. They need to decide: invest, hold, or divest.',
    'Portfolio: streaming (high growth, low margin), news media (declining), sports networks (stable), publishing (declining), gaming (high growth), cable TV (high margin but declining).',
    ['Total revenue: $10B','Streaming: $2B revenue, growing 30%, 5% margin','News: $1.5B, declining 10%, 15% margin','Sports: $2B, stable, 35% margin','Publishing: $0.5B, declining 15%, 10% margin','Gaming: $1B, growing 40%, 20% margin','Cable: $3B, declining 5%, 30% margin','Market cap: $8B','Debt: $2B','Competitors: Disney, Netflix, Comcast','Investment backlog: $2B requested across all units'],
    ['Portfolio value analysis (market sizing, margins, growth)','Investment prioritization framework','Divestiture candidates and valuation','Hold strategy for mature but profitable units','Merger or partnership opportunities for scale'],
    ['Profitability contribution by unit (revenue, margin, EBITDA)','Growth rate and market share trajectory','Investment ROI by unit','Divestiture proceeds and tax impact','3-year portfolio value under different strategies'],
    ['Portfolio recommendation (invest/hold/divest for each unit)','Divestiture candidates and buyer identification','Investment prioritization and sequencing','Financial projections under portfolio changes','Risk mitigation and execution plan']),
  c('ma-08','Private Equity Platform Build','M&A / Corporate Strategy','Private Equity / Technology','Expert',
    'A PE firm ($500M fund) wants to build a platform company in the $50B US commercial real estate services market by acquiring and integrating 5-8 small brokerage firms.',
    'US CRE services market: $50B (brokerage, property management, valuation, advisory). Highly fragmented with 20,000+ small firms. Platform play could create a market leader.',
    ['Fund size: $500M equity, can borrow 3x','Market: US CRE services, $50B fragmented','Target: 5-8 acquisitions ($50-200M each)','Platform synergies: cross-sell, tech consolidation, procurement','Management: need experienced CRE platform executive','Returns: 3x MOIC target, 5 year hold','Integration challenge: different systems, cultures, geographies','Buyer universe: 20,000+ small CRE firms','Average firm: $25M revenue, 10% margin','Industry consolidation trend: accelerating'],
    ['Target prioritization (size, geography, service mix)','Integration playbook (IT, brand, operations)','Value creation levers (revenue synergies, cost optimization)','Financing structure for platform build','Management team strategy'],
    ['Pro-forma financial model at target scale','Synergy realization timeline and value','IRR analysis under different acquisition sequences','Capital structure optimization','Platform value creation roadmap'],
    ['Target acquisition strategy','Integration playbook and execution plan','Financing and capital structure','Management team and governance','3-year value creation plan and exit readiness']),
  c('ma-09','Pharmaceutical Company Divestiture','M&A / Corporate Strategy','Pharmaceuticals','Hard',
    'A large pharma company ($40B revenue) wants to divest its non-core consumer healthcare division ($5B revenue) to focus on biologics and oncology. Evaluate the divestiture.',
    'Consumer healthcare: OTC medications, vitamins, supplements. Growing 3% but low margin vs pharma core. Multiple potential buyers. $5B in divestiture proceeds expected.',
    ['Company revenue: $40B','Consumer division: $5B revenue, 10% EBITDA margin','Biologics: $20B, 25% margin, growing 12%','Oncology: $15B, 30% margin, growing 15%','Consumer division: OTC, vitamins, supplements','Market: consumer healthcare $100B, growing 3%','Buyer interest: 5+ potential acquirers','Valuation estimate: $8-10B (16-20x EBITDA)','Proceeds use: pay down $5B debt, reinvest in biologics','Integration cost: $200M for separation','Employee impact: 3,000 consumer division employees','Regulatory: antitrust risk if buyer is large'],
    ['Divestiture rationale and strategic fit analysis','Buyer identification and valuation modeling','Separation planning (IT, supply chain, workforce)','Tax optimization for divestiture proceeds','Dividend or share buyback analysis for proceeds'],
    ['Divestiture valuation range ($8-10B)','Net proceeds after taxes and costs','EPS accretion/dilution analysis','Buyer competitive landscape','Timeline for separation and transition'],
    ['Divestiture recommendation with valuation','Buyer shortlist and outreach strategy','Separation execution plan','Proceeds allocation recommendation','Risk mitigation for regulatory and operational challenges']),
  c('ma-10','Aerospace Components Roll-Up','M&A / Corporate Strategy','Aerospace / Defense','Expert',
    'A mid-market aerospace company ($2B revenue) wants to create a leading platform in aerospace components and MRO (maintenance, repair, overhaul) through 8-12 acquisitions.',
    'Aerospace aftermarket is $100B, growing 5% annually. Highly fragmented. 2,000+ small MRO shops. Platform consolidation could capture 3-5% market share ($3-5B).',
    ['Company revenue: $2B (existing platform)','Target market: aerospace MRO, $100B, growing 5%/yr','Acquisitions needed: 8-12 ($100-300M each)','Target geography: US (60%), Europe (30%), Asia (10%)','Average target: $150M revenue, 10% margin','Valuation: 6-8x EBITDA (industry standard)','Platform synergies: procurement (15% savings), technology, cross-sell','Integration challenge: different repair certifications, IT systems','Management: 2,000+ technicians (certified per FAA regulations)','Political risk: defense contracts require US ownership','Competition: Heico, TransDigm have executed similar roll-ups'],
    ['Target identification and prioritization (certifications, geography, size)','Integration playbook (IT systems, certifications, talent)','Value creation levers (procurement, cross-sell, standardization)','Financing strategy (leveraged buyout structure)','Regulatory approval process for defense contracts'],
    ['Pro-forma P&L at target scale','IRR analysis with different deal multiples','Synergy realization timeline by value lever','Financing structure and covenant compliance','Portfolio risk (customer concentration, geographic exposure)'],
    ['Acquisition strategy with target framework','Integration playbook and execution plan','Financing and capital structure optimization','Management and talent retention plan','3-year value creation roadmap to exit readiness']),
];

// ======== DIGITAL TRANSFORMATION (20 cases) ========
const digital: any[] = [
  c('dt-01','Insurance Legacy Modernization','Digital Transformation','Insurance','Expert',
    'A 100-year-old insurance company ($10B premiums) runs on mainframe systems from the 1980s. They need to modernize to compete with insurtechs.',
    '5M policyholders, 10K independent agents. Policy issuance: 2 weeks (insurtechs: 5 minutes). Claims processing: 15 days (insurtechs: 2 days). IT spend: 3% of premium.',
    ['Premiums: $10B','Policyholders: 5M','Distribution: 100% via 10K independent agents','Core: Mainframe (COBOL), 30+ years old','IT budget: $300M (3% of premiums, benchmark 5%)','New policy: 2 weeks (insurtech: 5 minutes)','Claims: 15 days (insurtech: 2 days)','IT debt: $200M deferred maintenance','40 years of claims data, mostly inaccessible','Regulatory: 50 state regulators','Agent age: avg 55, low digital literacy','Customer age: avg 52','Insurtechs: 2% to 8% market share in 5 years'],
    ['Legacy modernization approach (big bang vs incremental)','Architecture strategy (microservices, APIs, cloud)','Build vs buy vs partner for digital capabilities','Data strategy and AI/ML implementation','Organizational change management'],
    ['Modernization cost and timeline estimates','ROI analysis for different approaches','Efficiency improvements ($/policy)','Revenue impact from improved CX','Risk assessment for each approach'],
    ['Modernization roadmap (phased)','Technology architecture recommendation','Investment and resource plan','Change management and talent strategy','Business case with quantified benefits']),
  c('dt-02','Restaurant Digital Ordering','Digital Transformation','Restaurant / F&B','Easy',
    'A fast-casual restaurant chain with 1,000 locations has only 10% digital orders. Target 40% in 2 years.',
    'Customizable bowls and salads. Avg check $12. Peak wait 30 minutes. Outdated website, no mobile app.',
    ['Locations: 1,000 (US only)','Revenue: $3.5B','Digital orders: 10% (industry 25%)','Target: 40% digital in 2 years','Peak wait: 30 minutes','Ticket: $12 (digital expected $14-15)','Competitors: Chipotle 40%, Sweetgreen 50%','POS: 5 years old, limited APIs','Kitchen: bowl made to order ~3 minutes','IT budget: $20M ($15M for digital transformation)'],
    ['Customer experience design (ordering, pick-up, loyalty)','Technology stack (mobile app, web, POS integration)','Operational integration (kitchen display, order routing)','Marketing and adoption strategy','Data and personalization capabilities'],
    ['Digital investment and ROI','Operational impact (throughput, labor)','Revenue uplift from higher ticket size','Customer acquisition cost for app downloads','Breakeven and payback analysis'],
    ['Digital product vision and feature roadmap','Technology platform recommendation','Operations integration plan','Customer adoption strategy','Financial projections and business case']),
  c('dt-03','Manufacturing Industry 4.0 Journey','Digital Transformation','Manufacturing / Industrial','Hard',
    'A 80-year-old industrial manufacturer ($5B revenue) wants to implement Industry 4.0 across 20 factories worldwide. Legacy equipment, limited digital talent, skeptical workforce.',
    'Heavy machinery for mining and construction. 70% equipment over 15 years old, not connected. Few IoT pilots. 3 major implementation failures in past decade.',
    ['Revenue: $5B, 20 factories in 12 countries','Digital maturity: Level 1 (basic automation, no IIoT)','Equipment: 70% non-connected, avg age 15 years','IT budget: $150M (3%, industry avg 4%)','Requested: $500M over 5 years','Potential: 20% OEE improvement, 15% energy, 10% labor efficiency','Pilot: 2 factories with IoT, 12% OEE gain','Workforce: 25K, avg age 48, 60% unionized','IT team: 200, mostly ERP, limited data science','Competitors: 2 major rivals have smart factories','Technologies: IoT sensors, edge computing, digital twin, AI/ML','ROI: 3x within 5 years','Past failures: 3 major turnaround projects','Customer pressure: demanding carbon footprint data'],
    ['Technology architecture and standards','Factory prioritization and lighthouse approach','Make vs buy vs partner for digital capabilities','Change management and workforce upskilling','Data strategy and governance'],
    ['Factory-level digital maturity assessment','Investment per factory and company-wide budget','Expected benefits (OEE, energy, quality) quantification','ROI analysis by factory and overall program','Talent and resourcing requirements'],
    ['Digital transformation roadmap with phased approach','Technology architecture and platform recommendations','Change management and workforce strategy','Investment and resource plan with ROI analysis','Governance and KPI framework for tracking']),
  c('dt-04','University Digital Learning Transformation','Digital Transformation','Education','Medium',
    'A traditional 200-year-old university with 30,000 students wants to transform digital learning. Losing market share to online universities and bootcamps.',
    'Strong brand, elite faculty, beautiful campus. Only 15% of courses online. Student satisfaction with digital: 30%. IT outdated.',
    ['Students: 30K (25K undergrad, 5K grad)','Revenue: $1.2B (tuition 60%, research 25%, endowment 15%)','Online course penetration: 15% (peer avg 40%)','Student digital satisfaction: 30% (target 80%)','IT budget: $60M (5%, peer avg 8%)','Core systems: 25-year-old ERP, no LMS, no analytics','Faculty interest: 30% in online teaching','Competition: Southern New Hampshire (135K online), ASU (60K)','Adult learner market: 40M Americans','Target: 50 online programs, 10K additional students in 3 years','Investment needed: $100M (tech, content, faculty training)','Current online revenue: $30M (potential: $200M+)'],
    ['Digital learning model selection (online vs hybrid)','Technology platform strategy (LMS, CRM, analytics)','Program prioritization (which degrees to digitize first)','Faculty engagement and IP rights','Student experience design and support services'],
    ['Investment by initiative and total program budget','Revenue projections for online programs','Cost savings from digital delivery','Enrollment targets and breakeven analysis','Technology platform cost comparison'],
    ['Digital learning vision and target operating model','Program launch roadmap with prioritization','Technology platform recommendation','Faculty engagement and capability building plan','Student experience and support services design']),
];

// ======== TURNAROUND / RESTRUCTURING (20 cases) ========
const turnaround: any[] = [
  c('tr-01','Department Store Chain Rescue','Turnaround / Restructuring','Retail','Medium',
    'A 50-year-old department store chain (200 locations) is in decline. Revenue dropped 30% in 5 years. Burning $100M cash annually. 12 months of runway.',
    'Mid-tier segment (Macy\'s, JCPenney territory). Squeezed by luxury upstairs and discount downstairs. Owns 60% of real estate.',
    ['Revenue: $2B (down from $2.8B in 5 years)','EBITDA: -$50M (burning $100M cash annually)','Cash: $150M (12 months runway)','Debt: $400M (covenants may be breached next quarter)','Stores: 200 (60% owned, 40% leased)','Store size: 80,000 sq ft (too large for modern retail)','Sales/sq ft: $150 ($200 industry avg)','E-commerce: 10% (industry avg 20%)','Private label: 15% of sales','Inventory turns: 3x (industry avg 4x)','Employees: 15,000','Lease obligations: $150M annually'],
    ['Cash conservation and liquidity management','Store portfolio optimization (closures, renegotiations)','Revenue recovery strategies (assortment, pricing, experience)','Cost restructuring (SG&A, occupancy, labor)','Capital structure and stakeholder management'],
    ['Cash flow forecast and liquidity runway','Store closure/renegotiation savings','Revenue stabilization trajectory','Capital structure restructuring scenarios','Turnaround investment requirements'],
    ['Cash stabilization plan (immediate 90 days)','Store footprint optimization plan','Revenue recovery strategy','Cost reduction targets','Timeline to profitability']),
  c('tr-02','Law Firm Partner Productivity Crisis','Turnaround / Restructuring','Professional Services / Legal','Medium',
    'A prestigious law firm (500 attorneys) sees partner profits declining 15% annually. Associates burning out. Billable hours dropping.',
    '80 years old, known for corporate law. "Up or out" partnership model. Competition from larger firms and nimble boutiques.',
    ['Revenue: $500M (flat 3 years)','Profits per partner: $500K (down from $700K in 5 years)','Equity partners: 100, Non-equity: 100','Associates: 300','Billable hours target: 2,000/yr','Utilization: 70% (was 80%)','Associate attrition: 25% annually (benchmark 18%)','Rates: Partners $800-1,200, Associates $400-800','Alt fee arrangements: 10% of revenue (benchmark 20%)','IT spend: 3% (benchmark 5%)','Doc automation: 20% (leading firms 60%)','Client concentration: Top 10 = 60% revenue','Practice mix: M&A 30%, Litigation 25%, Corporate 25%, Tax 20%'],
    ['Operating model transformation (alternative staffing, leverage)','Technology and automation adoption','Pricing and billing innovation','Talent management (recruitment, development, retention)','Practice mix optimization and client strategy'],
    ['Financial impact of leverage model changes','Technology investment and ROI','Associate retention improvement financial benefit','Alternative fee arrangement impact on profitability','Partner compensation model redesign'],
    ['Root cause diagnosis of profit decline','Operating model redesign recommendations','Technology and innovation roadmap','Talent strategy (recruit, develop, retain)','3-year profitability recovery plan']),
  c('tr-03','Manufacturing Turnaround','Turnaround / Restructuring','Manufacturing','Hard',
    'A European industrial manufacturer ($3B revenue) has lost 40% of revenue over 4 years. Plants running at 50% capacity. Need to restructure for survival.',
    'Heavy equipment manufacturer. Chinese competition undercutting prices. Energy costs doubled. Two plants are cash-negative.',
    ['Revenue: $3B (down from $5B in 4 years)','EBITDA: -$100M (was $300M positive)','Plants: 8 in Europe, utilization 50%','Cash burn: $100M/year','Debt: $2B (covenants under pressure)','Workforce: 15,000 (down from 22,000)','Chinese competition: 30-40% lower prices','Energy costs: doubled in 2 years','Key customers: 5 = 60% of revenue','Customer churn: 20% annually','Two plants cash-negative: -$50M combined'],
    ['Immediate cash conservation (days 1-90)','Plant closure/consolidation evaluation','Revenue recovery through pricing and contracts','Cost restructuring (labor, energy, overhead)','Debt renegotiation with lenders'],
    ['Cash flow model: survival under different scenarios','Plant closure impact on customers and workforce','Revenue recovery assumptions and sensitivity','Cost reduction runway and targets','Debt restructuring terms'],
    ['Immediate cash stabilization plan','Plant closure/consolidation recommendation','Revenue recovery and commercial strategy','Cost restructuring program','Debt renegotiation strategy']),
  c('tr-04','Telecom Network Infrastructure Turnaround','Turnaround / Restructuring','Telecommunications','Expert',
    'A European telecom ($15B revenue) has 12M subscribers but is losing 200K annually. 5G investment required but debt is 5x EBITDA. Need turnaround while investing.',
    'Network quality declining. Brand perception poor (2.1/5). Churn 3% monthly (benchmark 1.5%). 4G coverage: 75%. Customer NPS: -15.',
    ['Revenue: $15B (declining 5% annually)','Subscribers: 12M (losing 200K/year)','EBITDA: $5B (margin 33%)','Debt: $25B (5x EBITDA)','Churn: 3% monthly (benchmark 1.5%)','Brand NPS: -15 (worst in industry)','4G coverage: 75% (competitors 95%)','Customer satisfaction: 35th percentile','5G requirement: regulatory mandate','Capital needed: $5B over 5 years','Cost structure: 40% labor, 25% network, 20% spectrum, 15% overhead'],
    ['Network quality improvement (customer experience first)','Cost reduction (labor, real estate, procurement)','Subscriber acquisition and retention strategy','5G investment phasing and prioritization','Organizational restructuring'],
    ['Subscriber base stabilization (stop the bleeding)','Cost reduction from 40% overhead to 25%','5G investment ROI under phased rollout','Brand perception improvement roadmap','Debt reduction timeline from 5x to 3x EBITDA'],
    ['90-day stabilization plan','Cost reduction program with specific targets','Network quality and 5G investment roadmap','Subscriber retention and acquisition strategy','5-year turnaround to investment grade']),
  c('tr-05','Retail Chain Store Closure and Rebranding','Turnaround / Restructuring','Retail','Easy',
    'A 30-year-old specialty retailer (500 stores) has 40% of stores below profitability threshold. Revenue $2B, declining 8% annually. Need to right-size and rebrand.',
    'Stores are mostly in secondary locations. Average store size 15K sq ft (large for specialty). Online 20% of sales but growing. Customer age skewing older (avg 55).',
    ['Revenue: $2B (declining 8%/year)','Store count: 500 (40% below profitability threshold)','Revenue per store: $4M average','Store format: 15K sq ft (too large for specialty)','Online: 20% of sales, growing 20%','Customer avg age: 55 (target 35-45)','Lease obligations: $300M/year','Closing cost: $50M per store (lease termination, severance)','Remaining cash: $100M','Debt: $500M at 7%','Brand perception: dated, not aspirational'],
    ['Store closure strategy (which stores, when, how)','Brand repositioning and marketing refresh','Digital channel acceleration','Cost structure right-sizing for remaining footprint','Real estate portfolio renegotiation'],
    ['Store closure savings (labor, rent, utilities)','Revenue risk analysis from closures','Digital investment ROI','Brand refresh cost and impact','Lease renegotiation savings opportunity'],
    ['Store closure plan (150 stores in 18 months)','Brand repositioning and marketing strategy','Digital channel investment and growth','Cost structure targets and timeline','Financial projections and risk assessment']),
];

// ======== NEW BUSINESS / INNOVATION (20 cases) ========
const innovation: any[] = [
  c('nb-01','Carbon Credit Marketplace','New Business / Innovation','Climate Tech / Finance','Expert',
    'A climate tech startup ($20M seed) wants to build a transparent, high-integrity carbon credit marketplace connecting project developers with corporate buyers.',
    'Voluntary carbon market: $2B in 2023, projected $50B by 2030 (Bloomberg NEF). 70% of credits are low-quality. Corporate commitments: 1,000+ companies with net-zero targets.',
    ['Market: $2B in 2023, projected $50B by 2030','Credit quality: 70% low-quality (Berkeley study)','Corporate commitments: 1,000+ companies net-zero targets','Microsoft spent $50M on carbon removal in 2023','Verra and Gold Standard: dominant registries but slow','Their tech: blockchain traceability, satellite verification, AI quality scoring','Revenue model: 5-15% commission on trades','Target buyers: Fortune 500 sustainability teams','Competition: CTX, Xpansiv, Puro.earth','Capital raised: $20M seed, target Series A $50M','Key risk: carbon price volatility ($5-100/tonne)'],
    ['Platform strategy (marketplace vs registry vs financing)','Credit quality assurance and verification methodology','Liquidity creation and market making approach','Buyer and seller acquisition strategy','Revenue model and competitive positioning'],
    ['Marketplace take rate economics','GMV projection under adoption scenarios','Investment in credit verification vs commission generated','Series A requirement and path to profitability','Carbon price risk management strategy'],
    ['Business model recommendation with revenue projections','Credit quality assurance and technology differentiation','Go-to-market strategy (buyers, sellers, registries)','Funding requirements and path to Series A','Risk mitigation for carbon price volatility']),
  c('nb-02','Autonomous Delivery Network','New Business / Innovation','Logistics / Robotics','Hard',
    'A robotics company ($100M revenue, 5 years old) has developed autonomous delivery robots. They want to build a robot delivery network for urban areas, starting with 5 cities.',
    'Current: selling robots to universities and campuses ($50K each, 1,000 deployed). Unit economics: $50K robot cost, $2K/year maintenance, $10K/year service revenue. Urban delivery is 10x larger market.',
    ['Revenue: $100M (hardware + service)','Robot cost: $50K','Service revenue: $2K/year/robot','Installed base: 1,000 robots','Market: urban delivery $50B','Robot performance: 99.5% uptime, 5mph speed, 50lb capacity','Regulatory: 8 of 50 US states permit autonomous delivery','Competition: Nuro ($10B), Starship (1,000 robots), Amazon Scout','Funding: $200M raised, $500M needed for urban launch','Customer acquisition: $500/order (B2B contracts)','Route density: 200+ deliveries/day for profitability','Weather challenges: rain/snow reduce capacity 30%'],
    ['Market sizing and city selection','Regulatory strategy for autonomous delivery','Robot fleet scaling (manufacturing and maintenance)','Customer acquisition (B2B contracts with retailers/restaurants)','Safety and insurance framework'],
    ['Robot cost reduction trajectory ($50K to $20K over 3 years)','Service revenue per robot vs deployment cost','Urban delivery unit economics by city','Regulatory investment and timeline by state','Total addressable market and penetration scenarios'],
    ['Urban delivery network strategy with city prioritization','Robot manufacturing and deployment plan','Customer acquisition and contract structure','Regulatory and safety framework','Financial model and path to profitability']),
  c('nb-03','AI-Powered Personal Fitness Coach','New Business / Innovation','Health & Fitness / AI','Medium',
    'A fitness technology company ($50M revenue) wants to launch an AI-powered personal fitness coach subscription ($30/month) that creates personalized workout plans, nutrition advice, and real-time form feedback.',
    'Market: $10B global fitness tech. Competitors: Peloton ($3.5B, hardware+subscription), Apple Fitness+ ($10/month), Nike Training ($15/month). Their advantage: 10 years of user data from existing fitness tracking app (5M users).',
    ['Revenue: $50M (existing app: $10/month, 5M users, 500K subscribers)','Target: $200M ARR in 3 years','Competitors: Peloton $3.5B, Apple Fitness+ $10/mo, Nike $15/mo','Market: $10B global fitness tech, growing 15%/yr','User data: 5M users with 10 years of activity data','AI capabilities: basic ML for recommendations, no form analysis','Content: 100 workout plans, need 10,000 for personalization','Team: 200 employees (40 engineers, 60 trainers, 50 marketing, 50 ops)','CAC: $30 (current app), target $20 for premium','Pricing: $30/month = $360/year, $1,800 LTV if 5-year retention','Competitor conversion: Peloton 5% of free users, Apple 3%'],
    ['AI personalization engine development','Workout content creation and curation (10,000+ plans)','Form analysis technology (camera-based or wearable data)','Subscription tier design (Basic $10, Premium $30, Elite $50)','Marketing strategy to convert existing users + new acquisition'],
    ['Revenue projections: 500K → 2M premium subscribers in 3 years','Content creation cost: $5M for 10,000 plans','AI development cost: $15M over 2 years','CAC target of $20 vs competitor benchmarks','Unit economics: $30/mo - $5/mo COGS = $25/mo contribution margin'],
    ['AI fitness coach product roadmap','Content strategy and trainer partnerships','Pricing and subscription tier design','Marketing and customer acquisition plan','Financial model and path to $200M ARR']),
  c('nb-04','Digital Twin Supply Chain Platform','New Business / Innovation','Supply Chain / Technology','Hard',
    'An industrial IoT company ($200M revenue) wants to launch a digital twin platform for supply chain optimization. They have 50,000 IoT sensors deployed and supply chain data from 200 clients.',
    'The platform would enable real-time visibility, predictive analytics, and scenario simulation across global supply chains. TAM: $30B by 2030. Current clients include Fortune 500 manufacturers.',
    ['Revenue: $200M (hardware + basic software)','IoT sensors deployed: 50,000 across 200 clients','Supply chain data: real-time from 200 enterprise clients','Platform TAM: $30B by 2030, 20% CAGR','Competitors: SAP (digital twin module), Siemens (MindSphere), Microsoft (Azure Digital Twins)','Competitor pricing: $500K-2M/year platform fees','Their advantage: 10+ years of supply chain data, 50,000 sensor network','Development cost: $50M over 2 years','Target customers: Fortune 500 manufacturers and retailers','Target ARR: $200M within 5 years','Gross margin target: 75% (software) vs 40% (hardware)','Sales team: 50 enterprise account executives (need 150)'],
    ['Platform development strategy (build, buy, or partner)','Data moat and competitive differentiation','Enterprise sales and customer success model','Integration with existing client relationships','Go-to-market strategy (land-and-expand vs horizontal)'],
    ['ARR growth: $0 → $200M in 5 years','Gross margin trajectory: 40% (current) → 75% (software-first)','CAC: $50K target per $200K ARR account','Customer retention and expansion revenue','Development cost vs timeline vs competitive window'],
    ['Digital twin platform product roadmap','Go-to-market and sales strategy','Customer acquisition and retention plan','Technology development investment and timeline','Financial model and path to $200M ARR']),
  c('nb-05','Blockchain-Based Supply Chain Finance','New Business / Innovation','Finance / Blockchain','Expert',
    'A global bank ($200B assets) wants to launch a blockchain-based supply chain finance platform connecting manufacturers, suppliers, and distributors with dynamic discounting and trade finance.',
    'Current supply chain finance market: $50B. Blockchain can reduce settlement from 30 days to 1 day. The bank has 2,000 enterprise clients and existing trade finance relationships.',
    ['Bank assets: $200B, revenue $20B','Supply chain finance market: $50B','Blockchain cost savings: 40% vs traditional trade finance','Settlement improvement: 30 days → 1 day','Competitors: JPMorgan (Onyx), Goldman (Marcus), TradeShift','Platform development cost: $100M over 3 years','Target clients: 2,000 enterprise relationships','Revenue model: transaction fees (0.5-1%), interest spread, FX fees','Target ARR: $500M within 5 years','Regulatory complexity: cross-border, KYC/AML compliance','Current trade finance volume: $5B annually','Gross margin target: 60% for digital platform'],
    ['Blockchain platform architecture and technology selection','Customer segmentation and targeting strategy','Regulatory compliance framework (cross-border, KYC/AML)','Partnership ecosystem (manufacturers, carriers, insurers)','Pricing model and transaction fee structure'],
    ['Platform development cost and timeline','Revenue model: transaction volume × fee structure','Customer acquisition: 500 enterprise accounts in 3 years','Operating cost per transaction vs traditional model','Break-even timeline and ROI analysis'],
    ['Blockchain supply chain finance platform launch strategy','Technology and architecture recommendations','Customer acquisition and partnership plan','Regulatory compliance framework','Financial model and path to $500M ARR']),
];

// ======== COMPILE ALL CASES ========
const all = [
  // Load existing generated cases
  ...JSON.parse(fs.readFileSync(path.join(__dirname, '../../data/generated-cases.json'), 'utf-8')),
  ...gs, ...ops, ...ma, ...maMore, ...digital, ...turnaround, ...innovation,
];

// Deduplicate by id
const seen = new Set<string>();
const unique = all.filter((c: any) => { if (seen.has(c.id)) return false; seen.add(c.id); return true; });

// Write to generated-cases.json
const jsonPath = path.join(__dirname, '../../data/generated-cases.json');
fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
fs.writeFileSync(jsonPath, JSON.stringify(unique, null, 0), 'utf-8');
console.log(`Total unique cases: ${unique.length}`);

// Count by category
const counts: Record<string, number> = {};
unique.forEach((c: any) => { counts[c.category] = (counts[c.category] || 0) + 1; });
console.log('Cases by category:');
Object.entries(counts).forEach(([cat, count]) => console.log(`  ${cat}: ${count}`));